#!/bin/bash

su - postgres -c "echo -e \"Haciendo copias de seguridad\""
su - postgres -c "echo -e \"\\pset tuples_only \n select nombredb from empresa;\" | psql metabd" > listdb.lst

#Lineas=`wc -l listdb.lst`
#echo $Lineas
#echo $(Lineas[1])
#numlin=$($Lineas[1]-1)
#echo "$numlin"

for x in `tail +2 listdb.lst`
do
echo -e "Trataremos la base de datos $x"
echo -e "Hacemos copia de seguridad"
 su - postgres -c "pg_dump $x" > $x.pgdump
echo -e "Aplicamos parcheado de la version 0.3.7"
 su - postgres -c "psql $x"  < dbmodels/rev-0_3_7.sql  2> errores.txt > /dev/null
 echo -e "-----------------\n"
done

# tail -1 listdb.lst
# rm listdb.lst

