#!/bin/bash


touch errores.txt
echo -e "Comprobando versiones anteriores\n"

if [ -e /etc/bulmages.conf ]; then
#  Hacemos una actualizacion de las bases de datos.
   su - postgres -c "echo -e \"\\pset tuples_only \n select nombredb from empresa;\" | psql metabd" > listdb.lst
   for x in `tail +2 listdb.lst`
   do
      echo -e "Trataremos la base de datos $x"
      echo -e "Hacemos copia de seguridad"
      mkdir backup
      su - postgres -c "pg_dump $x" > backup/$x.pgdump
      for y in `ls dbmodels/rev-*.sql | sort`
      do
         echo -e "Evaluamos: " $y
         if [ ! -e /usr/share/bulmages/$y ]; then
	    su - postgres -c "psql $x "  < $y  2>> errores.txt >> errores.txt
	    echo -e "Actualizamos la version $y"
         fi
      done
      echo -e "-----------------\n"
   done

   echo -e "Tratamos la metabase"
   for y in `ls dbmodels/revmeta-*.sql | sort`
   do
      echo -e "Evaluamos: " $y
      if [ ! -e /usr/share/bulmages/$y ]; then
         su - postgres -c "psql metabd " < $y 2>> errores.txt >> errores.txt
	 echo -e "Actualizamos la version $y"
      fi
   done
   echo -e "------------------\n"


   cp /etc/bulmages.conf bulmages.conf.old

   for j in `ls rev-bulmages*.conf | sort`
   do
      if [ ! -e /usr/share/bulmages/$j ]; then
         echo -e "Aplicamos parche $j a bulmages.conf"
	 cat $j >> /etc/bulmages.conf
      fi
   done
   
   # Presentamos los errores acaecidos
   cat errores.txt | grep ERROR
else


# Hacemos una insercion inicial de las bases de datos.
   echo -e "Creando directorio /usr/share/bulmages\n"
   mkdir /usr/share/bulmages
   
   echo -e "Creando bases de datos \n"
   su - postgres -c "dropdb  bulmages" 2>> errores.txt > /dev/null
   su - postgres -c "createdb bulmages" 2>> errores.txt > /dev/null
   su - postgres -c "psql bulmages" < dbmodels/bulmages.pgdump 2>> errores.txt > /dev/null
   su - postgres -c "dropdb bgplangcont" 2>> errores.txt > /dev/null
   su - postgres -c "createdb bgplangcont" 2>> errores.txt > /dev/null
   su - postgres -c "psql bgplangcont" < dbmodels/bgplangcont.pgdump 2>> errores.txt > /dev/null
   su - postgres -c "dropdb metabd" 2>> errores.txt > /dev/null
   su - postgres -c "createdb metabd" 2>> errores.txt > /dev/null
   su - postgres -c "psql metabd" < dbmodels/metabd.pgdump 2>> errores.txt > /dev/null
   
   # Tratamos el archivo de configuracion
   echo -e "Copiando la nueva version de bulmages.conf\n"
   cp bulmages.conf /etc

   # Presentamos los errores acaecidos
   cat errores.txt | grep ERROR
   
   # Vamos a crear el usuario que acceda a la base de datos.
   echo Indique el usuario que va a trabajar normalmente con el programa:
   read user
   su - postgres -c "createuser --adduser --createdb $user"
fi

# Copiamos todos los archivos de la nueva version a sus localizaciones normales.
echo -e "Copiando archivos de imagenes\n"
cp *.jpg /usr/share/bulmages
cp *.png /usr/share/bulmages

echo -e "Copiando ejecutables\n"
cp bulmages /usr/local/bin
cp cargaemp /usr/local/bin
cp nuevaemp /usr/local/bin
cp borraremp /usr/local/bin
cp guardaemp /usr/local/bin
cp cargaemp /usr/local/bin

echo -e "Copiando archivos de revision de bulmages.conf\n"
cp rev-* /usr/share/bulmages

echo -e "Copiando archivos auxiliares\n"
cp -r dbmodels /usr/share/bulmages
cp -r backgrounds /usr/share/bulmages
cp -r ayuda /usr/share/bulmages
cp -r reports /usr/share/bulmages
cp -r css /usr/share/bulmages
cp -r icons /usr/share/bulmages
cp -r traducciones /usr/share/bulmages

