.TH nuevaemp 1 User Manuals
.SH NAME
nuevaemp \- creates a enterprise for bulmacont accounting program
.SH SYNOPSIS
\fBnuevaemp
\f1
.SH DESCRIPTION
nuevaemp is used to create one enterprise for bulmacont, a accounting program for small amd midle bussines.
.SH AUTHOR
bugupdate was written by the IGLUES team <info\@iglues.org>
.SH REPORTING BUGS
Report bugs to <info\@iglues.org>
.SH COPYRIGHT
Copyright (C) 2005 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO war- ranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH COMMENTS
This man page was written using \fBxmltoman(1)\f1.
