#!/bin/sh

# --------------------------------------------------
# Script para la creacion de una nueva emrpesa.
# $1 nombre del archivo de la base de datos
# --------------------------------------------------

cd /usr/share/bulmages/dbmodels
source creabulmages --texto $1 1 "Empresa vacia" 2004 metabd

