#ifndef PDEFS_PLUGINBF_CLIENTEPRESUPUESTO_H
#define PDEFS_PLUGINBF_CLIENTEPRESUPUESTO_H


#ifdef WIN32

#ifdef PLUGINBF_CLIENTEPRESUPUESTO
#define PLUGINBF_CLIENTEPRESUPUESTO_EXPORT __declspec(dllexport)
#else
#define PLUGINBF_CLIENTEPRESUPUESTO_EXPORT __declspec(dllimport)
#endif

#else

#define PLUGINBF_CLIENTEPRESUPUESTO_EXPORT

#endif


#endif

