/***************************************************************************
 *                                                                         *
 *   BulmaTPV remote client for Nintendo DS console.                       *
 *   -----------------------------------------------                       *
 *                                                                         *
 *   Copyright (C) 2010 by Fco. Javier M. C.                               *
 *   comercial@todo-redes.com                                              *
 *   http://www.todo-redes.com                                             *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation, either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>. *
 *                                                                         *
 ***************************************************************************/

#include "bndssocket.h"
#include "bndsfunctions.h"


BndsSocket::BndsSocket()
{
}


BndsSocket::~BndsSocket()
{
}


void BndsSocket::startWifi()
{

    /// Inicia la consola.
    PrintConsole conSub = g_video->consoleSub();
    consoleSelect( &conSub );

    m_status = ASSOCSTATUS_DISCONNECTED;

#ifdef DEMO

    m_status = ASSOCSTATUS_ASSOCIATED;

#else

    consoleClear();
    iprintf("Llamando al router (espere).\n");

    /// Comprueba los parametros minimos.
    if (accessPointSsid() == "") {
	iprintf("Error: No se ha establecido el SSID del router Wifi.\n");
	return;
    } // end if
    if (accessPointWep128Key() == "") {
	iprintf("Error: No se ha establecido una clave Wep128.\n");
	return;
    } // end if

    
    m_ap = findAP(accessPointSsid());
        
    //this tells the wifi lib to use dhcp for everything
    Wifi_SetIP(0,0,0,0,0);
    
    //unsigned char llave[26] = "F94A1A15BD888291A6E8C2F3F0";
    //unsigned char llave[26] = {0xF9, 0x4A, 0x1A, 0x15, 0xBD, 0x88, 0x82, 0x91, 0xA6, 0xE8, 0xC2, 0xF3, 0xF0};
    //u8 *key = &llave[0];
    //Wifi_ConnectAP(m_ap, WEPMODE_128BIT, 0, key);

    unsigned char* llave = (unsigned char*) strHex2IntWep128( accessPointWep128Key() ).data(); 
    u8 *key = &llave[0];
    Wifi_ConnectAP(m_ap, WEPMODE_128BIT, 0, key );

    /// Inicia la consola.
    consoleSelect( &conSub );

    
    int contador = 0;
    while(m_status != ASSOCSTATUS_ASSOCIATED && m_status != ASSOCSTATUS_CANNOTCONNECT)
    {

	    m_status = Wifi_AssocStatus();

	    iprintf("\x1b[0;0HAsociando router: %-14.14s", ASSOCSTATUS_STRINGS[m_status]);

	    iprintf("\x1b[1;%iH.", contador);

	    scanKeys();
	    contador++;
	    if (contador > 31) {
		/// Borra la linea.
		iprintf("\x1b[2K");
	    } // end if

	    swiWaitForVBlank();
	    
    } // end while

#endif
    
    consoleClear();

    if (m_status == ASSOCSTATUS_CANNOTCONNECT) {
	iprintf("\x1b[0;0H%-32.32s", "Asociado al router [ERROR].");
    } else if (m_status == ASSOCSTATUS_ASSOCIATED) {
	iprintf("\x1b[0;0H%-32.32s", "Asociado al router [OK].");
    } // end if

}



void BndsSocket::openServerSocket()
{

#ifdef DEMO

#else

    m_status = Wifi_AssocStatus();
    
    if(m_status == ASSOCSTATUS_ASSOCIATED) {
      
	// Create a TCP socket
	m_socket = socket( AF_INET, SOCK_STREAM, 0 ); 
	
	// Tell the socket to connect to the IP address we found, on port 80 (HTTP)
	
	struct sockaddr_in sain;
	sain.sin_family = AF_INET;
	
	sain.sin_port = htons(11637);
	//unsigned long ip = 0x0100007F; // IP. localhost 1.0.0.127
	
	unsigned long ip = ipToLong( ipServer() );
	
	char *addr = (char *)&ip;
	sain.sin_addr.s_addr= *( (unsigned long *)( addr )); // IP. localhost 127.0.0.1

	connect( m_socket,(struct sockaddr *)&sain, sizeof(sain) );
	
    } // end if

#endif

}


void BndsSocket::closeServerSocket()
{

#ifdef DEMO

#else

    m_status = Wifi_AssocStatus();

    if(m_status == ASSOCSTATUS_ASSOCIATED) {

	shutdown(m_socket,0); // good practice to shutdown the socket.

    } // end if

#endif

}


int BndsSocket::sendDataToServer(string data)
{

#ifdef DEMO

#else

    m_status = Wifi_AssocStatus();

    if(m_status == ASSOCSTATUS_ASSOCIATED) {
      
	const char* datos = data.c_str();
	unsigned int datosLenght = strlen(datos);
	unsigned int bytesSend;

	/// Si el tamanyo de lo que se quiere enviar es grande
	/// entonces se envia a trozos.
	while(datosLenght > 0) {
	  
	    bytesSend = send( m_socket, datos, datosLenght, 0 );
	  
	    //bytesSent = send(sd, s, length);
	    if (bytesSend == 0)
		break; //socket probably closed
	    else if (bytesSend < 0)
		break; //handle errors appropriately
	    datos += bytesSend;
	    datosLenght -= bytesSend;
	} // end while
      
    } // end if

#endif

    return 0;
}


string BndsSocket::readDataFromServer()
{
    string datos = "";

    /// Inicia la consola.
    PrintConsole conSub = g_video->consoleSub();
    consoleSelect( &conSub );
    consoleClear();

#ifdef DEMO

    datos = "";

#else

    int recvd_len;
    char incoming_buffer[256];

    while( ( recvd_len = recv( m_socket, incoming_buffer, 255, 0 ) ) != 0 ) { // if recv returns 0, the socket has been closed.

      if (recvd_len>0) { // data was received!
	    incoming_buffer[recvd_len] = 0; // null-terminate
	    //iprintf( incoming_buffer);
	    datos += incoming_buffer;
      } // end if
      
    } // end while

#endif

    return datos;
}


string BndsSocket::pullCategoryArticles()
{

	string datos = "<CATEGORIA>\
<CODCATEGORIA>005</CODCATEGORIA>\
<NOMCATEGORIA>Aperitivos</NOMCATEGORIA>\
<ARTICULO>\
<IDARTICULO>106</IDARTICULO>\
<NOMARTICULO>Aceituna Anchoa</NOMARTICULO>\
<PVPARTICULO>1.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>107</IDARTICULO>\
<NOMARTICULO>Aceituna Manza.</NOMARTICULO>\
<PVPARTICULO>1.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>105</IDARTICULO>\
<NOMARTICULO>Aceituna Negra</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>104</IDARTICULO>\
<NOMARTICULO>Almendra</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>111</IDARTICULO>\
<NOMARTICULO>Bits</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>112</IDARTICULO>\
<NOMARTICULO>Boca Bits</NOMARTICULO>\
<PVPARTICULO>1.20</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>110</IDARTICULO>\
<NOMARTICULO>Bugles 3Ds</NOMARTICULO>\
<PVPARTICULO>1.20</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>128</IDARTICULO>\
<NOMARTICULO>Cacahuete Miel</NOMARTICULO>\
<PVPARTICULO>1.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>108</IDARTICULO>\
<NOMARTICULO>Cacahuetes</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>113</IDARTICULO>\
<NOMARTICULO>Che. Pandilla</NOMARTICULO>\
<PVPARTICULO>1.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>145</IDARTICULO>\
<NOMARTICULO>Datil Bacon</NOMARTICULO>\
<PVPARTICULO>2.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>116</IDARTICULO>\
<NOMARTICULO>Doritos Tex-Mex</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>117</IDARTICULO>\
<NOMARTICULO>Fritos</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>144</IDARTICULO>\
<NOMARTICULO>Galletas Tuc</NOMARTICULO>\
<PVPARTICULO>2.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>109</IDARTICULO>\
<NOMARTICULO>Ganchito</NOMARTICULO>\
<PVPARTICULO>1.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>143</IDARTICULO>\
<NOMARTICULO>Gublins</NOMARTICULO>\
<PVPARTICULO>0.90</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>129</IDARTICULO>\
<NOMARTICULO>Maiz Frito</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>127</IDARTICULO>\
<NOMARTICULO>Nachos</NOMARTICULO>\
<PVPARTICULO>3.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>140</IDARTICULO>\
<NOMARTICULO>Nueces</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>138</IDARTICULO>\
<NOMARTICULO>Orejones Albari.</NOMARTICULO>\
<PVPARTICULO>1.20</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>139</IDARTICULO>\
<NOMARTICULO>Palomitas</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>142</IDARTICULO>\
<NOMARTICULO>Papa Delta</NOMARTICULO>\
<PVPARTICULO>9.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>118</IDARTICULO>\
<NOMARTICULO>Pat. Artesanas</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>119</IDARTICULO>\
<NOMARTICULO>Pat. Campesina</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>120</IDARTICULO>\
<NOMARTICULO>Pat. Gourmet</NOMARTICULO>\
<PVPARTICULO>1.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>121</IDARTICULO>\
<NOMARTICULO>Pat. Jamon</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>122</IDARTICULO>\
<NOMARTICULO>Pat. Light</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>126</IDARTICULO>\
<NOMARTICULO>Pat. Punto Sal</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>115</IDARTICULO>\
<NOMARTICULO>Pelotazos</NOMARTICULO>\
<PVPARTICULO>1.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>136</IDARTICULO>\
<NOMARTICULO>Pipas</NOMARTICULO>\
<PVPARTICULO>1.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>141</IDARTICULO>\
<NOMARTICULO>Pipas Tijuana</NOMARTICULO>\
<PVPARTICULO>1.10</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>137</IDARTICULO>\
<NOMARTICULO>Pistacho</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>130</IDARTICULO>\
<NOMARTICULO>Pringles</NOMARTICULO>\
<PVPARTICULO>2.90</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>131</IDARTICULO>\
<NOMARTICULO>Pringles Cebolla</NOMARTICULO>\
<PVPARTICULO>2.90</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>132</IDARTICULO>\
<NOMARTICULO>Pringles C. Peq.</NOMARTICULO>\
<PVPARTICULO>1.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>133</IDARTICULO>\
<NOMARTICULO>Pringles Peq.</NOMARTICULO>\
<PVPARTICULO>1.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>135</IDARTICULO>\
<NOMARTICULO>Pringles Q. Peq.</NOMARTICULO>\
<PVPARTICULO>1.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>134</IDARTICULO>\
<NOMARTICULO>Pringles Queso</NOMARTICULO>\
<PVPARTICULO>2.90</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>124</IDARTICULO>\
<NOMARTICULO>Ruffles Jamon</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>125</IDARTICULO>\
<NOMARTICULO>Ruffles Original</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>123</IDARTICULO>\
<NOMARTICULO>Stax</NOMARTICULO>\
<PVPARTICULO>2.20</PVPARTICULO>\
</ARTICULO>\
</CATEGORIA>\
\
\
<CATEGORIA>\
<CODCATEGORIA>002</CODCATEGORIA>\
<NOMCATEGORIA>Bebidas</NOMCATEGORIA>\
<ARTICULO>\
<IDARTICULO>16</IDARTICULO>\
<NOMARTICULO>Agua</NOMARTICULO>\
<PVPARTICULO>1.10</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>92</IDARTICULO>\
<NOMARTICULO>Agua con gas</NOMARTICULO>\
<PVPARTICULO>1.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>87</IDARTICULO>\
<NOMARTICULO>Agua cristal</NOMARTICULO>\
<PVPARTICULO>1.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>58</IDARTICULO>\
<NOMARTICULO>Agua Peque</NOMARTICULO>\
<PVPARTICULO>0.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>89</IDARTICULO>\
<NOMARTICULO>Aquarius</NOMARTICULO>\
<PVPARTICULO>1.45</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>90</IDARTICULO>\
<NOMARTICULO>Aquarius Naranja</NOMARTICULO>\
<PVPARTICULO>1.45</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>36</IDARTICULO>\
<NOMARTICULO>Bat. Chocolate</NOMARTICULO>\
<PVPARTICULO>1.20</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>85</IDARTICULO>\
<NOMARTICULO>Burn</NOMARTICULO>\
<PVPARTICULO>2.90</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>86</IDARTICULO>\
<NOMARTICULO>Burn B.</NOMARTICULO>\
<PVPARTICULO>3.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>2</IDARTICULO>\
<NOMARTICULO>Cocacola</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>66</IDARTICULO>\
<NOMARTICULO>Cocacola Bot</NOMARTICULO>\
<PVPARTICULO>1.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>19</IDARTICULO>\
<NOMARTICULO>Cocacola Light</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>68</IDARTICULO>\
<NOMARTICULO>Cocacola Light Bot</NOMARTICULO>\
<PVPARTICULO>1.35</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>21</IDARTICULO>\
<NOMARTICULO>Cocacola Sin</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>20</IDARTICULO>\
<NOMARTICULO>Cocacola Zero</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>67</IDARTICULO>\
<NOMARTICULO>Cocacola Zero Bot</NOMARTICULO>\
<PVPARTICULO>1.35</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>22</IDARTICULO>\
<NOMARTICULO>Fanta Limon</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>70</IDARTICULO>\
<NOMARTICULO>Fanta L. Zero</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>56</IDARTICULO>\
<NOMARTICULO>Fanta Naranja</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>69</IDARTICULO>\
<NOMARTICULO>Fanta N. Zero</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>95</IDARTICULO>\
<NOMARTICULO>Fanta Verdia</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>59</IDARTICULO>\
<NOMARTICULO>Guarana</NOMARTICULO>\
<PVPARTICULO>1.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>94</IDARTICULO>\
<NOMARTICULO>Kas Limon</NOMARTICULO>\
<PVPARTICULO>1.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>93</IDARTICULO>\
<NOMARTICULO>Kas Naranja</NOMARTICULO>\
<PVPARTICULO>1.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>23</IDARTICULO>\
<NOMARTICULO>La Casera</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>91</IDARTICULO>\
<NOMARTICULO>Lipton Ice</NOMARTICULO>\
<PVPARTICULO>1.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>24</IDARTICULO>\
<NOMARTICULO>Nestea</NOMARTICULO>\
<PVPARTICULO>1.55</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>224</IDARTICULO>\
<NOMARTICULO>Nestea Sin</NOMARTICULO>\
<PVPARTICULO>1.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>220</IDARTICULO>\
<NOMARTICULO>Okey Chocolate</NOMARTICULO>\
<PVPARTICULO>1.25</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>221</IDARTICULO>\
<NOMARTICULO>Okey Fresa</NOMARTICULO>\
<PVPARTICULO>1.25</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>222</IDARTICULO>\
<NOMARTICULO>Okey Vainilla</NOMARTICULO>\
<PVPARTICULO>1.25</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>62</IDARTICULO>\
<NOMARTICULO>Pepsi</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>114</IDARTICULO>\
<NOMARTICULO>Pepsi Bot</NOMARTICULO>\
<PVPARTICULO>1.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>88</IDARTICULO>\
<NOMARTICULO>Pepsi Light</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>63</IDARTICULO>\
<NOMARTICULO>Pepsi Twist</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>28</IDARTICULO>\
<NOMARTICULO>Radical</NOMARTICULO>\
<PVPARTICULO>2.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>61</IDARTICULO>\
<NOMARTICULO>Red Bull</NOMARTICULO>\
<PVPARTICULO>3.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>65</IDARTICULO>\
<NOMARTICULO>Schweppes</NOMARTICULO>\
<PVPARTICULO>1.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>83</IDARTICULO>\
<NOMARTICULO>Schweppes Bot.</NOMARTICULO>\
<PVPARTICULO>1.20</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>64</IDARTICULO>\
<NOMARTICULO>Schweppes Citrus</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>84</IDARTICULO>\
<NOMARTICULO>Schweppes Citrus Bot.</NOMARTICULO>\
<PVPARTICULO>1.20</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>15</IDARTICULO>\
<NOMARTICULO>Seven up</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>25</IDARTICULO>\
<NOMARTICULO>Sprite</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>54</IDARTICULO>\
<NOMARTICULO>Zumo Manzana</NOMARTICULO>\
<PVPARTICULO>1.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>57</IDARTICULO>\
<NOMARTICULO>Zumo Melocoton</NOMARTICULO>\
<PVPARTICULO>1.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>26</IDARTICULO>\
<NOMARTICULO>Zumo Naranja</NOMARTICULO>\
<PVPARTICULO>1.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>60</IDARTICULO>\
<NOMARTICULO>Zumo piña</NOMARTICULO>\
<PVPARTICULO>1.60</PVPARTICULO>\
</ARTICULO>\
</CATEGORIA>\
\
\
<CATEGORIA>\
<CODCATEGORIA>004</CODCATEGORIA>\
<NOMCATEGORIA>Bocadillos</NOMCATEGORIA>\
<ARTICULO>\
<IDARTICULO>199</IDARTICULO>\
<NOMARTICULO>B. Anchoas</NOMARTICULO>\
<PVPARTICULO>3.10</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>71</IDARTICULO>\
<NOMARTICULO>B. Atun</NOMARTICULO>\
<PVPARTICULO>2.95</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>198</IDARTICULO>\
<NOMARTICULO>B. Atun Pimi.</NOMARTICULO>\
<PVPARTICULO>3.10</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>74</IDARTICULO>\
<NOMARTICULO>B. Bacon Queso</NOMARTICULO>\
<PVPARTICULO>3.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>102</IDARTICULO>\
<NOMARTICULO>B. Calamares</NOMARTICULO>\
<PVPARTICULO>3.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>103</IDARTICULO>\
<NOMARTICULO>B. Chistorra</NOMARTICULO>\
<PVPARTICULO>3.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>204</IDARTICULO>\
<NOMARTICULO>B. Chopped</NOMARTICULO>\
<PVPARTICULO>2.85</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>80</IDARTICULO>\
<NOMARTICULO>B. Chorizo</NOMARTICULO>\
<PVPARTICULO>2.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>77</IDARTICULO>\
<NOMARTICULO>B. Fuet</NOMARTICULO>\
<PVPARTICULO>2.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>73</IDARTICULO>\
<NOMARTICULO>Bikini</NOMARTICULO>\
<PVPARTICULO>2.45</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>97</IDARTICULO>\
<NOMARTICULO>B. Jamon Queso</NOMARTICULO>\
<PVPARTICULO>2.90</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>202</IDARTICULO>\
<NOMARTICULO>B. Jamon York</NOMARTICULO>\
<PVPARTICULO>2.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>81</IDARTICULO>\
<NOMARTICULO>B. Pate</NOMARTICULO>\
<PVPARTICULO>2.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>203</IDARTICULO>\
<NOMARTICULO>B. Pavo Queso</NOMARTICULO>\
<PVPARTICULO>2.90</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>78</IDARTICULO>\
<NOMARTICULO>B. Pollo</NOMARTICULO>\
<PVPARTICULO>3.10</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>98</IDARTICULO>\
<NOMARTICULO>B. Queso</NOMARTICULO>\
<PVPARTICULO>2.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>96</IDARTICULO>\
<NOMARTICULO>B. Salami</NOMARTICULO>\
<PVPARTICULO>2.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>100</IDARTICULO>\
<NOMARTICULO>B. Salchichon</NOMARTICULO>\
<PVPARTICULO>2.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>201</IDARTICULO>\
<NOMARTICULO>B. Serraco Queso</NOMARTICULO>\
<PVPARTICULO>3.25</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>72</IDARTICULO>\
<NOMARTICULO>B. Serrano</NOMARTICULO>\
<PVPARTICULO>3.20</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>197</IDARTICULO>\
<NOMARTICULO>B. Sobrasada</NOMARTICULO>\
<PVPARTICULO>2.90</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>196</IDARTICULO>\
<NOMARTICULO>B. Tort. France.</NOMARTICULO>\
<PVPARTICULO>3.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>79</IDARTICULO>\
<NOMARTICULO>B. Tortilla Patata</NOMARTICULO>\
<PVPARTICULO>3.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>82</IDARTICULO>\
<NOMARTICULO>B. Vegetal</NOMARTICULO>\
<PVPARTICULO>3.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>76</IDARTICULO>\
<NOMARTICULO>Frankfurt</NOMARTICULO>\
<PVPARTICULO>2.95</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>75</IDARTICULO>\
<NOMARTICULO>Pepito Lomo</NOMARTICULO>\
<PVPARTICULO>3.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>101</IDARTICULO>\
<NOMARTICULO>Pepito Ternera</NOMARTICULO>\
<PVPARTICULO>3.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>200</IDARTICULO>\
<NOMARTICULO>Sandwich Mixto</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>205</IDARTICULO>\
<NOMARTICULO>Sandwich Queso</NOMARTICULO>\
<PVPARTICULO>1.30</PVPARTICULO>\
</ARTICULO>\
</CATEGORIA>\
\
\
<CATEGORIA>\
<CODCATEGORIA>003</CODCATEGORIA>\
<NOMCATEGORIA>Cerveza</NOMCATEGORIA>\
<ARTICULO>\
<IDARTICULO>212</IDARTICULO>\
<NOMARTICULO>Buckler 00</NOMARTICULO>\
<PVPARTICULO>2.20</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>213</IDARTICULO>\
<NOMARTICULO>Buckler 00 Lata</NOMARTICULO>\
<PVPARTICULO>2.10</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>38</IDARTICULO>\
<NOMARTICULO>Budweiser</NOMARTICULO>\
<PVPARTICULO>2.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>215</IDARTICULO>\
<NOMARTICULO>Budweiser Lata</NOMARTICULO>\
<PVPARTICULO>2.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>40</IDARTICULO>\
<NOMARTICULO>Coronita</NOMARTICULO>\
<PVPARTICULO>2.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>41</IDARTICULO>\
<NOMARTICULO>Cruzcampo</NOMARTICULO>\
<PVPARTICULO>2.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>207</IDARTICULO>\
<NOMARTICULO>Cruzcampo Caña</NOMARTICULO>\
<PVPARTICULO>1.90</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>206</IDARTICULO>\
<NOMARTICULO>Cruzcampo Lata</NOMARTICULO>\
<PVPARTICULO>2.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>208</IDARTICULO>\
<NOMARTICULO>Cruzcampo Light</NOMARTICULO>\
<PVPARTICULO>2.10</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>209</IDARTICULO>\
<NOMARTICULO>Cruz. Light L.</NOMARTICULO>\
<PVPARTICULO>2.10</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>44</IDARTICULO>\
<NOMARTICULO>Heineken</NOMARTICULO>\
<PVPARTICULO>2.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>217</IDARTICULO>\
<NOMARTICULO>Heineken Lata</NOMARTICULO>\
<PVPARTICULO>2.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>48</IDARTICULO>\
<NOMARTICULO>Mahou 5 Es.</NOMARTICULO>\
<PVPARTICULO>2.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>219</IDARTICULO>\
<NOMARTICULO>Mahou 5 Lata</NOMARTICULO>\
<PVPARTICULO>2.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>46</IDARTICULO>\
<NOMARTICULO>Mahou Clasica</NOMARTICULO>\
<PVPARTICULO>2.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>223</IDARTICULO>\
<NOMARTICULO>Mahou Clas. Lata</NOMARTICULO>\
<PVPARTICULO>1.90</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>47</IDARTICULO>\
<NOMARTICULO>Mahou Negra</NOMARTICULO>\
<PVPARTICULO>2.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>49</IDARTICULO>\
<NOMARTICULO>Mixta</NOMARTICULO>\
<PVPARTICULO>2.10</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>218</IDARTICULO>\
<NOMARTICULO>Mixta Lata</NOMARTICULO>\
<PVPARTICULO>2.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>210</IDARTICULO>\
<NOMARTICULO>San Miguel 00</NOMARTICULO>\
<PVPARTICULO>2.10</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>211</IDARTICULO>\
<NOMARTICULO>San Miguel 00 Lat.</NOMARTICULO>\
<PVPARTICULO>2.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>214</IDARTICULO>\
<NOMARTICULO>Shandy</NOMARTICULO>\
<PVPARTICULO>1.95</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>216</IDARTICULO>\
<NOMARTICULO>Shandy Lata</NOMARTICULO>\
<PVPARTICULO>1.90</PVPARTICULO>\
</ARTICULO>\
</CATEGORIA>\
\
\
<CATEGORIA>\
<CODCATEGORIA>006</CODCATEGORIA>\
<NOMCATEGORIA>Helados</NOMCATEGORIA>\
<ARTICULO>\
<IDARTICULO>153</IDARTICULO>\
<NOMARTICULO>Coco Helado</NOMARTICULO>\
<PVPARTICULO>3.20</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>148</IDARTICULO>\
<NOMARTICULO>H. Aupa Cola</NOMARTICULO>\
<PVPARTICULO>1.20</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>149</IDARTICULO>\
<NOMARTICULO>H. Aupa Fresa</NOMARTICULO>\
<PVPARTICULO>1.20</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>150</IDARTICULO>\
<NOMARTICULO>H. Aupa Limon</NOMARTICULO>\
<PVPARTICULO>1.20</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>171</IDARTICULO>\
<NOMARTICULO>H. Bellice</NOMARTICULO>\
<PVPARTICULO>1.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>154</IDARTICULO>\
<NOMARTICULO>H. Cubanito</NOMARTICULO>\
<PVPARTICULO>1.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>175</IDARTICULO>\
<NOMARTICULO>H. Dove</NOMARTICULO>\
<PVPARTICULO>1.90</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>172</IDARTICULO>\
<NOMARTICULO>H. Fresi Nata</NOMARTICULO>\
<PVPARTICULO>1.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>176</IDARTICULO>\
<NOMARTICULO>H. Hawai</NOMARTICULO>\
<PVPARTICULO>1.10</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>194</IDARTICULO>\
<NOMARTICULO>H. Hero</NOMARTICULO>\
<PVPARTICULO>1.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>177</IDARTICULO>\
<NOMARTICULO>H. Kontiki</NOMARTICULO>\
<PVPARTICULO>1.55</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>195</IDARTICULO>\
<NOMARTICULO>H. Lacasitos</NOMARTICULO>\
<PVPARTICULO>2.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>178</IDARTICULO>\
<NOMARTICULO>H. Maltesers</NOMARTICULO>\
<PVPARTICULO>1.65</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>191</IDARTICULO>\
<NOMARTICULO>H. Mante. Trufa</NOMARTICULO>\
<PVPARTICULO>3.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>152</IDARTICULO>\
<NOMARTICULO>H. Marsy</NOMARTICULO>\
<PVPARTICULO>2.55</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>179</IDARTICULO>\
<NOMARTICULO>H. Maxi Fresa</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>155</IDARTICULO>\
<NOMARTICULO>H. M&M</NOMARTICULO>\
<PVPARTICULO>1.90</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>161</IDARTICULO>\
<NOMARTICULO>H. Morsy</NOMARTICULO>\
<PVPARTICULO>2.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>180</IDARTICULO>\
<NOMARTICULO>H. Mulato</NOMARTICULO>\
<PVPARTICULO>1.65</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>158</IDARTICULO>\
<NOMARTICULO>H. Nanuky</NOMARTICULO>\
<PVPARTICULO>2.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>181</IDARTICULO>\
<NOMARTICULO>H. Party</NOMARTICULO>\
<PVPARTICULO>1.45</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>157</IDARTICULO>\
<NOMARTICULO>H. PokerCrocant</NOMARTICULO>\
<PVPARTICULO>3.10</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>182</IDARTICULO>\
<NOMARTICULO>H. Prestige P.</NOMARTICULO>\
<PVPARTICULO>1.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>174</IDARTICULO>\
<NOMARTICULO>H. Punky</NOMARTICULO>\
<PVPARTICULO>2.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>162</IDARTICULO>\
<NOMARTICULO>H. Rodondo Cho.</NOMARTICULO>\
<PVPARTICULO>0.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>185</IDARTICULO>\
<NOMARTICULO>H. Rodondo Frut.</NOMARTICULO>\
<PVPARTICULO>0.90</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>166</IDARTICULO>\
<NOMARTICULO>H. Rodondo Leche</NOMARTICULO>\
<PVPARTICULO>0.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>186</IDARTICULO>\
<NOMARTICULO>H. Sandwich</NOMARTICULO>\
<PVPARTICULO>0.90</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>147</IDARTICULO>\
<NOMARTICULO>H. Sandy Pop</NOMARTICULO>\
<PVPARTICULO>1.10</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>183</IDARTICULO>\
<NOMARTICULO>H. Santory</NOMARTICULO>\
<PVPARTICULO>1.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>193</IDARTICULO>\
<NOMARTICULO>H. Smaily</NOMARTICULO>\
<PVPARTICULO>2.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>192</IDARTICULO>\
<NOMARTICULO>H. Snaky Taco</NOMARTICULO>\
<PVPARTICULO>1.45</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>169</IDARTICULO>\
<NOMARTICULO>H. Stilo</NOMARTICULO>\
<PVPARTICULO>1.30</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>187</IDARTICULO>\
<NOMARTICULO>H. Sumo</NOMARTICULO>\
<PVPARTICULO>1.55</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>167</IDARTICULO>\
<NOMARTICULO>H. Sumo Frutas</NOMARTICULO>\
<PVPARTICULO>1.55</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>188</IDARTICULO>\
<NOMARTICULO>H. Super Nut</NOMARTICULO>\
<PVPARTICULO>1.80</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>146</IDARTICULO>\
<NOMARTICULO>H. Truficono</NOMARTICULO>\
<PVPARTICULO>1.90</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>159</IDARTICULO>\
<NOMARTICULO>H. Trufito</NOMARTICULO>\
<PVPARTICULO>3.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>164</IDARTICULO>\
<NOMARTICULO>H. Trufo Almend.</NOMARTICULO>\
<PVPARTICULO>1.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>165</IDARTICULO>\
<NOMARTICULO>H. Trufo Blanco</NOMARTICULO>\
<PVPARTICULO>1.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>189</IDARTICULO>\
<NOMARTICULO>H. Trufo Frutas</NOMARTICULO>\
<PVPARTICULO>1.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>163</IDARTICULO>\
<NOMARTICULO>H. Trufo Straccia</NOMARTICULO>\
<PVPARTICULO>1.60</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>173</IDARTICULO>\
<NOMARTICULO>H. Vacky</NOMARTICULO>\
<PVPARTICULO>2.50</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>190</IDARTICULO>\
<NOMARTICULO>H. Xtra</NOMARTICULO>\
<PVPARTICULO>1.00</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>170</IDARTICULO>\
<NOMARTICULO>H. Zero</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>168</IDARTICULO>\
<NOMARTICULO>H.Zero Vaso</NOMARTICULO>\
<PVPARTICULO>1.40</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>184</IDARTICULO>\
<NOMARTICULO>H. Zoo Loco</NOMARTICULO>\
<PVPARTICULO>2.10</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>160</IDARTICULO>\
<NOMARTICULO>Limon Helado</NOMARTICULO>\
<PVPARTICULO>3.20</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>151</IDARTICULO>\
<NOMARTICULO>Naranja Helado</NOMARTICULO>\
<PVPARTICULO>3.20</PVPARTICULO>\
</ARTICULO>\
<ARTICULO>\
<IDARTICULO>156</IDARTICULO>\
<NOMARTICULO>Piña Helado</NOMARTICULO>\
<PVPARTICULO>3.20</PVPARTICULO>\
</ARTICULO>\
</CATEGORIA>";

	return datos;
}


