#ifndef PDEFS_PLUGINBT_PRINTERCOCINA_H
#define PDEFS_PLUGINBT_PRINTERCOCINA_H


#ifdef Q_OS_WIN32

#ifdef PLUGINBT_PRINTERCOCINA
#define PLUGINBT_PRINTERCOCINA_EXPORT __declspec(dllexport)
#else
#define PLUGINBT_PRINTERCOCINA_EXPORT __declspec(dllimport)
#endif

#else

#define PLUGINBT_PRINTERCOCINA_EXPORT

#endif


#endif

