#ifndef PDEFS_PLUGINBF_CLIENTEALBARANESFACTURA_H
#define PDEFS_PLUGINBF_CLIENTEALBARANESFACTURA_H


#ifdef Q_OS_WIN32

#ifdef PLUGINBF_CLIENTEALBARANESFACTURA
#define PLUGINBF_CLIENTEALBARANESFACTURA_EXPORT __declspec(dllexport)
#else
#define PLUGINBF_CLIENTEALBARANESFACTURA_EXPORT __declspec(dllimport)
#endif

#else

#define PLUGINBF_CLIENTEALBARANESFACTURA_EXPORT

#endif


#endif

