.TH bulmacont 1 User Manuals
.SH NAME
bulmacont \- accounting program
.SH SYNOPSIS
\fBbulmacont \fI[ database | user | password ]\fB
\f1
.SH DESCRIPTION
bulmacont is accounting program for small amd midle bussines.
.TP
\fBdatabase \f1
the database to connect. We recoment to use bulmasetup to install the example database suplied. 
.TP
\fBuser \f1
the user for the access to the database.
.TP
\fBpassword \f1
the user password for the access to the database.
.SH AUTHOR
bulmacont was written by the IGLUES team <info\@iglues.org>
.SH REPORTING BUGS
Report bugs to <info\@iglues.org>
.SH COPYRIGHT
Copyright (C) 2005 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO war- ranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH COMMENTS
This man page was written using \fBxmltoman(1)\f1.
.SH FILES
/etc/bulmages/bulmages.conf
.SH SEE ALSO
bulmasetup(1) bulmages.conf(1) bulmages(1) bulmafact(1) bulmatpv(1)
