#ifndef PDEFS_PLUGINBT_ALIASTALLASYCOLORES_H
#define PDEFS_PLUGINBT_ALIASTALLASYCOLORES_H


#ifdef Q_OS_WIN32

#ifdef PLUGINBT_ALIASTALLASYCOLORES
#define PLUGINBT_ALIASTALLASYCOLORES_EXPORT __declspec(dllexport)
#else
#define PLUGINBT_ALIASTALLASYCOLORES_EXPORT __declspec(dllimport)
#endif

#else

#define PLUGINBT_ALIASTALLASYCOLORES_EXPORT

#endif


#endif

