.TH bulmacont 1 User Manuals
.SH NAME
bulmacont \- setup program
.SH SYNOPSIS
\fBbulmasetup 
\f1
.SH DESCRIPTION
bulmasetup configures the databases for bulmages programs. It configures databases and ussers, adds plugins, and makes backups of databases.
.SH AUTHOR
bulmasetup was written by the IGLUES team <info\@iglues.org>
.SH REPORTING BUGS
Report bugs to <info\@iglues.org>
.SH COPYRIGHT
Copyright (C) 2005 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO war- ranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH COMMENTS
This man page was written using \fBxmltoman(1)\f1.
.SH FILES
/etc/bulmages/bulmages.conf
.SH SEE ALSO
bulmages(1) bulmages.conf(1) bulmacont(1) bulmacont.conf(1)  bulmafact(1) bulmafact.conf(1) bulmatpv(1) bulmatpv.conf(1)
