<table width="100%" cellspacing="0" cellpadding="0" border="0">
            <tr> 
                  <td align="left" height="30">&nbsp;</td>
            </tr>
            <tr> 
	       <td align="left" height="30"><font face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF" size="2"><a href="inicio.php">Quienes 
            Somos</a></font></td>
            </tr>
            <tr> 
<td align="left" height="30"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><a href="desarrollo.php">Desarrollo</a></font></td>
            </tr>
            <tr> 
<td align="left" height="30"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><a href="descarga.php">Descarga</a></font></td>
            </tr>
            <tr> 
<td align="left" height="30"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><a href="enlaces.php">Enlaces</a></font></td>
            </tr>

	 </table>

    