#ifndef PDEFS_PLUGINBF_MULTIIMPRIMIR_H
#define PDEFS_PLUGINBF_MULTIIMPRIMIR_H


#ifdef Q_OS_WIN32

#ifdef PLUGINBF_MULTIIMPRIMIR
#define PLUGINBF_MULTIIMPRIMIR_EXPORT __declspec(dllexport)
#else
#define PLUGINBF_MULTIIMPRIMIR_EXPORT __declspec(dllimport)
#endif

#else

#define PLUGINBF_MULTIIMPRIMIR_EXPORT

#endif


#endif

