#!/bin/bash

# (C) Tomeu Borras Riera, tborras@conetxia.com
# Script que hace enlaces de las aplicaciones a las ubicaciones pertienentes
# Debe ejecutarse como root

# Hace los enlaces desde el directorio de build de cmake.
# Hay cosas no enlazadas que deben asegurarse despues.

# Coge como parametro el fuente y el nombre del directorio de compilacion

rm /usr/bin/bulmacont
ln -s $1/$2/bulmacont/src/bulmacont /usr/bin/bulmacont

rm /usr/bin/bulmafact
ln -s $1/$2/bulmafact/src/bulmafact /usr/bin/bulmafact

rm /usr/bin/bulmatpv
ln -s $1/$2/bulmatpv/src/bulmatpv /usr/bin/bulmatpv

#rm /usr/bin/bgtrml2pdf.py
#ln -s $1/$2/bgtrml2pdf /usr/bin/bgtrml2pdf

rm /usr/bin/bgtrml2pdf
ln -s $1/$2/bgtrml2pdf /usr/bin/bgtrml2pdf


rm /usr/bin/bulmasetup
ln -s $1/$2/bulmasetup.py /usr/bin/bulmasetup
ln -s $1/bulmasetup /usr/share/bulmages

rm /usr/bin/bulmages
ln -s $1/$2/bulmages/src/bulmages /usr/bin/bulmages

rm -rf /usr/share/bulmages
ln -s $1/installbulmages /usr/share/bulmages

rm /usr/lib/libbulmalib*
ln -s $1/$2/bulmalib/src/libbulmalib.so /usr/lib/libbulmalib.so
ln -s $1/$2/bulmalib/src/libbulmalib.so.0 /usr/lib/libbulmalib.so.0
ln -s $1/$2/bulmalib/src/libbulmalib.so.0.11 /usr/lib/libbulmalib.so.0.11
ln -s $1/$2/bulmalib/src/libbulmalib.so.0.11.0 /usr/lib/libbulmalib.so.0.11.0

rm -rf /usr/lib/bulmages
rm -rf /usr/lib/bulmafact
rm -rf /usr/lib/bulmatpv
rm -rf /usr/lib/bulmacont
rm -rf /usr/lib/bulmalib

#ln -s $1/lib/bulmafact /usr/lib/bulmafact
#ln -s $1/lib/bulmatpv  /usr/lib/bulmatpv
#ln -s $1/lib/bulmacont /usr/lib/bulmacont
#ln -s $1/lib/bulmalib  /usr/lib/bulmalib

mkdir /usr/lib/bulmages
ln -s $1/installbulmages/bgtrml2pdf/bgcolor.py /usr/lib/bulmages
ln -s $1/installbulmages/bgtrml2pdf/bgutils.py /usr/lib/bulmages

mkdir /usr/lib/bulmacont
mkdir /usr/lib/bulmafact
mkdir /usr/lib/bulmatpv
mkdir /usr/lib/bulmalib

mkdir /usr/lib/bulmacont/plugins
mkdir /usr/lib/bulmafact/plugins
mkdir /usr/lib/bulmatpv/plugins
mkdir /usr/lib/bulmalib/plugins

#Instalacion de Plugins
find $1/$2/bulmafact/plugins/ -name "*.so" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/lib/bulmafact/plugins/
find $1/$2/bulmacont/plugins/ -name "*.so" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/lib/bulmacont/plugins/
find $1/$2/bulmalib/plugins/  -name "*.so" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/lib/bulmalib/plugins/
find $1/$2/bulmatpv/plugins/ -name "*.so" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/lib/bulmatpv/plugins/
find $1/$2/privateplugins/ -name "*.so" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/lib/bulmafact/plugins/

#Instalacion de los sql de los plugins
find $1/bulmafact/plugins/ -name "*.sql" | grep -v "CMake" | xargs -I '{}' ln -s '{}' /usr/share/bulmages/dbmodels/plugins/
find $1/bulmacont/plugins/ -name "*.sql" | grep -v "CMake" | xargs -I '{}' ln -s '{}' /usr/share/bulmages/dbmodels/plugins/
find $1/bulmalib/plugins/ -name "*.sql" | grep -v "CMake" | xargs -I '{}' ln -s '{}' /usr/share/bulmages/dbmodels/plugins/
find $1/bulmatpv/plugins/ -name "*.sql" | grep -v "CMake" | xargs -I '{}' ln -s '{}' /usr/share/bulmages/dbmodels/plugins/
find $1/privateplugins/ -name "*.sql" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/share/bulmages/dbmodels/plugins/

#Archivos adicionales de bulmafact que pertenezcan a los plugins.
find $1/bulmafact/plugins/ -name "*.png" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/share/bulmages/icons/
find $1/bulmafact/plugins/ -name "*.jpg" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/share/bulmages/icons/
find $1/bulmafact/plugins/ -name "*.xpn" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/share/bulmages/icons/
find $1/bulmafact/plugins/ -name "*.rml" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/share/bulmages/openreports/

#Archivos adicionales de bulmacont que pertenezcan a los plugins.
find $1/bulmacont/plugins/ -name "*.png" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/share/bulmages/icons/
find $1/bulmacont/plugins/ -name "*.jpg" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/share/bulmages/icons/
find $1/bulmacont/plugins/ -name "*.xpn" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/share/bulmages/icons/
find $1/bulmacont/plugins/ -name "*.rml" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/share/bulmages/openreports/
 
#Archivos adicionales de bulmalib que pertenezcan a los plugins.
find $1/bulmalib/plugins/ -name "*.png" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/share/bulmages/icons/
find $1/bulmalib/plugins/ -name "*.jpg" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/share/bulmages/icons/
find $1/bulmalib/plugins/ -name "*.xpn" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/share/bulmages/icons/
find $1/bulmalib/plugins/ -name "*.rml" | grep -v "CMake" |xargs -I '{}' ln -s '{}' /usr/share/bulmages/openreports/


