<script language="php">
$title = "Contactar con Iglues";
// =================================================
$body = '

<h1>Información de contacto</h1>
<P>Mayoritariamente IGLUES prefiere comunicarse a través de medios electrónicos o digitales.</P>
<P>La mejor forma de comunicación es a través de la lista de distribución</P>

<a href="home.php?go=maillists">bulmages@bulma.net</a>

<P>A pesar de ello no podemos librarnos de ciertos requisitos legales que nos obligan a tener presencia física.<P>
<PRE>
	Asociación Iglues
	C/ Joaquin Turina, 1 local 4
	07009 Palma de Mallorca (Baleares)
	
	Tel/Fax: 971 29 06 29
</PRE>

'; 
// =================================================
</script>