<script language="php">
$title = "Junta Directiva";
// =================================================
$body = '

<H1>Junta Directiva</H1>

<OL>
<LI> Presidente: <b>Josep Burción</b>. <br>Correo: <i>presidente at iglues.org</i><br></LI>
	
<LI> Vicepresidente: <b>René Mérou</b>. <br>Correo: <i>vicepresidente at iglues.org</i><br></LI>

<LI> Secretario: <b>Cristina Marco Hernández</b><br>Correo: <i>secretario at iglues.org</i><br></LI>

<LI> Tesorero: <b>Tomeu Borrás Riera</b><br>Correo: <i>tesorero at iglues.org</i><br> </LI>
<LI> Vocales: <b>Santiago Capel, Laura Edo, Pablo Braulio, Josep Maria Estopà</b></LI>

</OL>

<br>
El resto de socios también deberían ser vocales, según acuerdo en la asamblea. Para ello bastará la petición de serlo a la Junta Directiva.
<br>
'; 
// =================================================
</script>