#ifndef PDEFS_PLUGINBF_CLIENTEFACTURAIVAINC_H
#define PDEFS_PLUGINBF_CLIENTEFACTURAIVAINC_H


#ifdef Q_OS_WIN32

#ifdef PLUGINBF_CLIENTEFACTURAIVAINC
#define PLUGINBF_CLIENTEFACTURAIVAINC_EXPORT __declspec(dllexport)
#else
#define PLUGINBF_CLIENTEFACTURAIVAINC_EXPORT __declspec(dllimport)
#endif

#else

#define PLUGINBF_CLIENTEFACTURAIVAINC_EXPORT

#endif


#endif

