# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./bulmalib
# Target is a library:  bulmalib

LIBS += -lpq 
INCLUDEPATH = /usr/include/postgresql/ 
TARGET = bulmalib 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
HEADERS += configuracion.h \
           postgresiface2.h 
SOURCES += configuracion.cpp \
           postgresiface2.cpp 
