#!/bin/bash
###############################################################################
# Script de instalación de BulmaGés
# (C) Tomeu Borràs, y Rene Merou Septiempbre 2004
# Este documento/script se distribuye bajo licencia GPL
#------------------------------------------------------------------------------
# Parametros
#     $1 : --texto
#          --dialog (por defecto)
###############################################################################


# Primeros pinitos con archivos de Debian
#. /usr/share/debconf/confmodule
#db_version 2.0
#db_input low foo/bar || true
#db_go || true

#Buscamos el parametro para saber si es texto o no
if [ "$1" = "--texto" ]; then
  texto="1"
  ptexto="--texto"
else
  texto="0"
  ptexto="--dialog"
fi

#Borramos antiguos archivos que puedan dar problemas
if [ -e /tmp/errores.txt ]; then
rm -f /tmp/errores.txt
fi
if [ -e /tmp/listdb.lst ]; then
rm -f /tmp/listdb.lst
fi
if [ -e /tmp/listuser.lst ]; then
rm -f /tmp/listuser.lst
fi
if [ -e /tmp/error.txt ]; then
rm -f /tmp/error.txt
fi


# Esta funcion presenta mensajes por pantalla
function mensaje() {
   if [ ! -e /usr/bin/dialog -a ! -e /usr/bin/xdialog -o $texto = 1 ]; then
      echo -e "$2" "$1"  "$3"
   elif [ -e /usr/bin/xdialog ]; then
      xdialog --title "Instalacion de BulmaGes v0.5.1" --backtitle "Asociacion Iglues" --msgbox "$1" 10 60
   else
      dialog --title "Instalacion de BulmaGes v0.5.1" --backtitle "Asociacion Iglues" --msgbox "$1" 10 60
   fi
}

# Esta funcion presenta mensajes.
function info() {
   if [ ! -e /usr/bin/dialog -a ! -e /usr/bin/xdialog -o $texto = 1 ]; then
      echo -e  "$2" "$1"  "$3"
   elif [ -e /usr/bin/xdialog ]; then
      xdialog --title "Instalacion de BulmaGes v0.5.1" --backtitle "Asociacion Iglues" --infobox "$1" 10 60
   else
      dialog --title "Instalacion de BulmaGes v0.5.1" --backtitle "Asociacion Iglues" --infobox "$1" 10 60
   fi
}

#Esta funcion crea usuarios que van a manejar la base de datos.
function lee() {
   if [ ! -e /usr/bin/dialog -a ! -e /usr/bin/xdialog -o $texto = 1 ]; then
      echo -e  "\033[33m""Indique el usuario que va a trabajar normalmente con el programa:"  "\033[0m"
      read user
   elif [ -e /usr/bin/xdialog ]; then
      xdialog --title "Instalacion de BulmaGes v0.5.1" --inputbox "Nombre del usuario que va a trabajar normalmente con BulmaGes. \n deje el campo en blanco para terminar." 10 60  2>/tmp/dialog.ans
      user=`cat /tmp/dialog.ans`
      rm -f /tmp/dialog.ans # don't litter !
   else
      xdialog --title "Instalacion de BulmaGes v0.5.1" --inputbox "Nombre del usuario que va a trabajar normalmente con BulmaGes. \n deje el campo en blanco para terminar." 10 60  2>/tmp/dialog.ans
      user=`cat /tmp/dialog.ans`
      rm -f /tmp/dialog.ans # don't litter !
   fi
   while [ "$user" != "" ]
   do
      su - postgres -c "createuser --adduser --createdb $user"
      if [ ! -e /usr/bin/dialog -a ! -e /usr/bin/xdialog -o $texto = 1 ]; then
         echo -e  "\033[33m""Indique el usuario que va a trabajar normalmente con el programa:"  "\033[0m"
         read user
      elif [ -e /usr/bin/xdialog ]; then
         dialog --title "Instalacion de BulmaGes v0.5.1" --inputbox "Nombre del usuario que va a trabajar normalmente con BulmaGes. \n deje el campo en blanco para terminar." 10 60  2>/tmp/dialog.ans
         user=`cat /tmp/dialog.ans`
         rm -f /tmp/dialog.ans # don't litter !
      else
         dialog --title "Instalacion de BulmaGes v0.5.1" --inputbox "Nombre del usuario que va a trabajar normalmente con BulmaGes. \n deje el campo en blanco para terminar." 10 60  2>/tmp/dialog.ans
         user=`cat /tmp/dialog.ans`
         rm -f /tmp/dialog.ans # don't litter !
      fi
   done
}

function tiempo {
  sleep 1.5
}

function linea {
   if [ ! -e /usr/bin/dialog -a ! -e /usr/bin/xdialog -o $texto = 1 ]; then
     echo -e "\033[32m----------------------------------------------\033[0m\n"
   fi
}

# Comprobamos que estamos ejecutando como root el programa
if [ ! $(whoami) = "root" ]; then
   mensaje "Este script de instalacion debe ejecutarse como root. \n"
   exit 1
fi


# Iniciamos el tema de los errores.
if [ -e /tmp/errores.txt ]; then
    rm -f /tmp/errores.txt
fi

#Comprobamos que estamos en el directorio adecuado
if [ ! -e ./installbulmages ]; then
 mensaje "Directorio incorrecto. La instalacion debe ejecutarse desde el directorio donde se encuentra el script. \n"
 exit 1
fi

#Comprobamos que existe la libreria de qt adecuada.
LANG_PSQL=`locate libqt-mt.so.3`
if [ "$LANG_PSQL" = "" ]; then
	mensaje "Libreria de Qt libqt.so.3 no esta instalada o no se encuentra. \n"
	exit 1
fi


# Distinguimos entre una instalacion y una actualizacion
info "Comprobando versiones anteriores. \n" "\033[32m" "\033[0m"
tiempo

if [ -e /etc/bulmages.conf ]; then

   info "Creando el directorio /tmp/backup para guardar copias de seguridad de las bases de datos. \n"
   tiempo
   if [ -e /tmp/backup ]; then
      info -e "El directorio /tmp/backup ya existe. \n"
      linea
   else
      mkdir /tmp/backup
   fi

   # Tambien actualizarmos el fichero de backup.
   info "Realizando backup del archivo de configuracion."
   tiempo
   cp /etc/bulmages.conf bulmages.conf.old

   for j in `ls rev-bulmages*.conf | sort`
   do
      if [ ! -e /usr/share/bulmages/$j ]; then
         info "Aplicamos parche $j a bulmages.conf"
         cat $j >> /etc/bulmages.conf
      fi
   done

   # Presentamos los errores acaecidos
   if [ -e /tmp/errores.txt ]; then
      cat /tmp/errores.txt | grep ERROR
   fi
else


# Hacemos una insercion inicial de las bases de datos.
   info "Inicializando directorio /usr/share/bulmages.\n"
   tiempo
   if [ ! -e /usr/share/bulmages ]; then
      mkdir /usr/share/bulmages
   fi

# Copiamos todos los archivos de la nueva version a sus localizaciones normales.
info "Instalando archivos de imagenes de Splash y de logotipo. \n"
tiempo
cp *.jpg /usr/share/bulmages
cp *.png /usr/share/bulmages

info "Instalando ejecutable del programa y scripts auxiliares. \n"
tiempo
cp bulmages /usr/bin
cp cargaemp /usr/bin
cp guardaemp /usr/bin
cp nuevaemp  /usr/bin
cp bulmafact /usr/bin
cp bulmacont /usr/bin
#cp bulmatpv /usr/bin
cp rtkview /usr/bin
cp trml2pdf/* /usr/bin/

info "Instalando archivos de revision del archivo de configuracion. \n"
tiempo
cp rev-* /usr/share/bulmages

info "Instalando archivos de ayuda del programa, imagenes, iconos, listados y traducciones. \n"
tiempo
cp -r dbmodels /usr/share/bulmages
cp -r backgrounds /usr/share/bulmages
cp -r ayuda /usr/share/bulmages
cp -r reports /usr/share/bulmages
cp -r css /usr/share/bulmages
cp -r icons /usr/share/bulmages
cp -r traducciones /usr/share/bulmages
cp -r formularios /usr/share/bulmages
cp -r ainteligentes /usr/share/bulmages
cp -r balances /usr/share/bulmages
cp -r kugar /usr/share/bulmages
cp -r openreports /usr/share/bulmages


info "Instalando plugins iniciales. \n"
if [ ! -e /usr/lib/bulmages ]; then
        mkdir /usr/lib/bulmages
fi
cp -r plugins /usr/lib/bulmages
tiempo

info "Creando bases de datos del sistema y empresas de ejemplo. \n"
tiempo

# Creamos las bases de datos para bulmacont.
   su - postgres -c "/usr/share/bulmages/dbmodels/creabulmages $ptexto bulmages 2 Bulmages 2005"
   su - postgres -c "/usr/share/bulmages/dbmodels/creabulmages $ptexto bgplangcont 1 \"Plan Contable Vacio\" 2005"

# Creamos las bases de datos para bulmafact.
   su - postgres -c "/usr/share/bulmages/dbmodels/creabulmafact $ptexto bulmafact 1 \"Facturacion Vacia\" 2005 metabd"

   # Tratamos el archivo de configuracion
   info "Instalando la nueva version del archivo de configuracion. \n"
   cp bulmages.conf /etc

   # Presentamos los errores acaecidos
   if [ -e /tmp/errores.txt ]; then
      cat /tmp/errores.txt | grep ERROR
   fi

   # Dejamos que la insercion del usuario la haga una funcion y asi encapsulamos un poco.
   lee
fi

mensaje "INSTALACION FINALIZADA CON EXITO" "\033[32m" "\033[0m"

