#ifndef PDEFS_PLUGINBC_CUENTASANUALES2ODS_H
#define PDEFS_PLUGINBC_CUENTASANUALES2ODS_H


#ifdef Q_OS_WIN32

#ifdef PLUGINBC_CUENTASANUALES2ODS
#define PLUGINBC_CUENTASANUALES2ODS_EXPORT __declspec(dllexport)
#else
#define PLUGINBC_CUENTASANUALES2ODS_EXPORT __declspec(dllimport)
#endif

#else

#define PLUGINBC_CUENTASANUALES2ODS_EXPORT

#endif


#endif

