#ifndef PDEFS_PLUGINBF_INFORMECLIENTE_H
#define PDEFS_PLUGINBF_INFORMECLIENTE_H


#ifdef Q_OS_WIN32

#ifdef PLUGINBF_INFORMECLIENTE
#define PLUGINBF_INFORMECLIENTE_EXPORT __declspec(dllexport)
#else
#define PLUGINBF_INFORMECLIENTE_EXPORT __declspec(dllimport)
#endif

#else

#define PLUGINBF_INFORMECLIENTE_EXPORT

#endif


#endif

