# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/bulmatpv

TEMPLATE = app 
CONFIG += release \
          warn_on 
TARGET = ../bin/bulmatpv 
INCLUDEPATH = ../src \
              /usr/include/qt 
LIBS += -lqt-mt 
SOURCES += bulmatpv.cpp \
           main.cpp \
           tpvview.cpp 
HEADERS += bulmatpv.h \
           tpvview.h 
IDLS += tpvdlg.ui 
FORMS += tpvdlg.ui 
