#ifndef PDEFS_PLUGINBF_CLIENTEALBARAN_H
#define PDEFS_PLUGINBF_CLIENTEALBARAN_H


#ifdef Q_OS_WIN32

#ifdef PLUGINBF_CLIENTEALBARAN
#define PLUGINBF_CLIENTEALBARAN_EXPORT __declspec(dllexport)
#else
#define PLUGINBF_CLIENTEALBARAN_EXPORT __declspec(dllimport)
#endif

#else

#define PLUGINBF_CLIENTEALBARAN_EXPORT

#endif


#endif

