#ifndef PDEFS_PLUGINBT_TICKETDEVUELTO_H
#define PDEFS_PLUGINBT_TICKETDEVUELTO_H


#ifdef Q_OS_WIN32

#ifdef PLUGINBT_TICKETDEVUELTO
#define PLUGINBT_TICKETDEVUELTO_EXPORT __declspec(dllexport)
#else
#define PLUGINBT_TICKETDEVUELTO_EXPORT __declspec(dllimport)
#endif

#else

#define PLUGINBT_TICKETDEVUELTO_EXPORT

#endif


#endif

