Document: bulmages
Title: Debian bulmages Manual
Author: <insert document author here>
Abstract: This manual describes what bulmages is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bulmages/bulmages.sgml.gz

Format: postscript
Files: /usr/share/doc/bulmages/bulmages.ps.gz

Format: text
Files: /usr/share/doc/bulmages/bulmages.text.gz

Format: HTML
Index: /usr/share/doc/bulmages/html/index.html
Files: /usr/share/doc/bulmages/html/*.html

  
