# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bulmasetupbase.ui'
#
# Created: Wed Jun  3 16:58:37 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 400)
        MainWindow.setMinimumSize(QtCore.QSize(732, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/iglues.org.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(209, 209))
        self.label.setMaximumSize(QtCore.QSize(209, 209))
        self.label.setPixmap(QtGui.QPixmap(":/images/iglues.org.svg"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.nuevo_usuario = QtGui.QPushButton(self.groupBox_3)
        self.nuevo_usuario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.nuevo_usuario.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/add_user_postgresql.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nuevo_usuario.setIcon(icon1)
        self.nuevo_usuario.setIconSize(QtCore.QSize(38, 38))
        self.nuevo_usuario.setObjectName("nuevo_usuario")
        self.gridLayout_2.addWidget(self.nuevo_usuario, 0, 0, 1, 1)
        self.editar_usuario = QtGui.QPushButton(self.groupBox_3)
        self.editar_usuario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.editar_usuario.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/edit_user_postgresql.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editar_usuario.setIcon(icon2)
        self.editar_usuario.setIconSize(QtCore.QSize(38, 38))
        self.editar_usuario.setObjectName("editar_usuario")
        self.gridLayout_2.addWidget(self.editar_usuario, 0, 1, 1, 1)
        self.permisos_usuario = QtGui.QPushButton(self.groupBox_3)
        self.permisos_usuario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.permisos_usuario.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.permisos_usuario.setIcon(icon2)
        self.permisos_usuario.setIconSize(QtCore.QSize(38, 38))
        self.permisos_usuario.setObjectName("permisos_usuario")
        self.gridLayout_2.addWidget(self.permisos_usuario, 1, 0, 1, 1)
        self.eliminar_usuario = QtGui.QPushButton(self.groupBox_3)
        self.eliminar_usuario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.eliminar_usuario.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/trash_user_postgresql.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eliminar_usuario.setIcon(icon3)
        self.eliminar_usuario.setIconSize(QtCore.QSize(38, 38))
        self.eliminar_usuario.setObjectName("eliminar_usuario")
        self.gridLayout_2.addWidget(self.eliminar_usuario, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.mui_crearbulmacont = QtGui.QPushButton(self.groupBox_2)
        self.mui_crearbulmacont.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mui_crearbulmacont.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/iconbulmacont.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_crearbulmacont.setIcon(icon4)
        self.mui_crearbulmacont.setIconSize(QtCore.QSize(38, 38))
        self.mui_crearbulmacont.setObjectName("mui_crearbulmacont")
        self.gridLayout.addWidget(self.mui_crearbulmacont, 0, 0, 1, 1)
        self.mui_crearbulmafact = QtGui.QPushButton(self.groupBox_2)
        self.mui_crearbulmafact.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mui_crearbulmafact.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/iconbulmafact.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_crearbulmafact.setIcon(icon5)
        self.mui_crearbulmafact.setIconSize(QtCore.QSize(38, 38))
        self.mui_crearbulmafact.setObjectName("mui_crearbulmafact")
        self.gridLayout.addWidget(self.mui_crearbulmafact, 0, 1, 1, 1)
        self.mui_adminempresas = QtGui.QPushButton(self.groupBox_2)
        self.mui_adminempresas.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mui_adminempresas.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/manage_company.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_adminempresas.setIcon(icon6)
        self.mui_adminempresas.setIconSize(QtCore.QSize(32, 32))
        self.mui_adminempresas.setObjectName("mui_adminempresas")
        self.gridLayout.addWidget(self.mui_adminempresas, 1, 0, 1, 1)
        self.eliminar_empresa = QtGui.QPushButton(self.groupBox_2)
        self.eliminar_empresa.setFocusPolicy(QtCore.Qt.NoFocus)
        self.eliminar_empresa.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/trash_company.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eliminar_empresa.setIcon(icon7)
        self.eliminar_empresa.setIconSize(QtCore.QSize(32, 32))
        self.eliminar_empresa.setObjectName("eliminar_empresa")
        self.gridLayout.addWidget(self.eliminar_empresa, 1, 1, 1, 1)
        self.mui_restbackup = QtGui.QPushButton(self.groupBox_2)
        self.mui_restbackup.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mui_restbackup.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/restore_database.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_restbackup.setIcon(icon8)
        self.mui_restbackup.setIconSize(QtCore.QSize(32, 32))
        self.mui_restbackup.setObjectName("mui_restbackup")
        self.gridLayout.addWidget(self.mui_restbackup, 2, 1, 1, 1)
        self.mui_creabackup = QtGui.QPushButton(self.groupBox_2)
        self.mui_creabackup.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mui_creabackup.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/backup_database.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_creabackup.setIcon(icon9)
        self.mui_creabackup.setIconSize(QtCore.QSize(32, 32))
        self.mui_creabackup.setObjectName("mui_creabackup")
        self.gridLayout.addWidget(self.mui_creabackup, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(17, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtGui.QSpacerItem(388, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.mui_salir = QtGui.QPushButton(self.centralwidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/bulmasetup_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_salir.setIcon(icon10)
        self.mui_salir.setObjectName("mui_salir")
        self.horizontalLayout.addWidget(self.mui_salir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.mui_salir, QtCore.SIGNAL("released()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "BulmaSetup", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">BulmaSetup v 0.11</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Administracion de Bases</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">de Datos para BulmaGes</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Gestión de Usuarios", None, QtGui.QApplication.UnicodeUTF8))
        self.nuevo_usuario.setText(QtGui.QApplication.translate("MainWindow", "Nuevos Usuario de PostgreSQL", None, QtGui.QApplication.UnicodeUTF8))
        self.editar_usuario.setText(QtGui.QApplication.translate("MainWindow", "Editar Usuarios de PostgreSQL", None, QtGui.QApplication.UnicodeUTF8))
        self.permisos_usuario.setText(QtGui.QApplication.translate("MainWindow", "Modificar Permisos de PostgreSQL", None, QtGui.QApplication.UnicodeUTF8))
        self.eliminar_usuario.setText(QtGui.QApplication.translate("MainWindow", "Eliminar Usuarios de PostgreSQL", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Gestión de Empresas", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_crearbulmacont.setText(QtGui.QApplication.translate("MainWindow", "Nueva Empresa de Contabilidad", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_crearbulmafact.setText(QtGui.QApplication.translate("MainWindow", "Nueva Empresa de Facturación / TPV", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_adminempresas.setText(QtGui.QApplication.translate("MainWindow", "Administrar Empresas Existentes", None, QtGui.QApplication.UnicodeUTF8))
        self.eliminar_empresa.setText(QtGui.QApplication.translate("MainWindow", "Eliminar Empresas Existentes", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_restbackup.setText(QtGui.QApplication.translate("MainWindow", "Restaurar copia de seguridad", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_creabackup.setText(QtGui.QApplication.translate("MainWindow", "Crear Copia de Seguridad", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_salir.setText(QtGui.QApplication.translate("MainWindow", "Salir", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
