# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bulmasetupbase.ui'
#
# Created: Fri Feb 21 22:27:59 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(778, 400)
        MainWindow.setMinimumSize(QtCore.QSize(732, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/iglues.org.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(209, 209))
        self.label.setMaximumSize(QtCore.QSize(209, 400))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/logo1.png")))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.nuevo_usuario = QtGui.QPushButton(self.groupBox_3)
        self.nuevo_usuario.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.nuevo_usuario.setFont(font)
        self.nuevo_usuario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.nuevo_usuario.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/add_user_postgresql.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nuevo_usuario.setIcon(icon1)
        self.nuevo_usuario.setIconSize(QtCore.QSize(38, 38))
        self.nuevo_usuario.setObjectName(_fromUtf8("nuevo_usuario"))
        self.gridLayout_2.addWidget(self.nuevo_usuario, 0, 0, 1, 1)
        self.editar_usuario = QtGui.QPushButton(self.groupBox_3)
        self.editar_usuario.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.editar_usuario.setFont(font)
        self.editar_usuario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.editar_usuario.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/edit_user_postgresql.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editar_usuario.setIcon(icon2)
        self.editar_usuario.setIconSize(QtCore.QSize(38, 38))
        self.editar_usuario.setObjectName(_fromUtf8("editar_usuario"))
        self.gridLayout_2.addWidget(self.editar_usuario, 0, 1, 1, 1)
        self.permisos_usuario = QtGui.QPushButton(self.groupBox_3)
        self.permisos_usuario.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.permisos_usuario.setFont(font)
        self.permisos_usuario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.permisos_usuario.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.permisos_usuario.setIcon(icon2)
        self.permisos_usuario.setIconSize(QtCore.QSize(38, 38))
        self.permisos_usuario.setObjectName(_fromUtf8("permisos_usuario"))
        self.gridLayout_2.addWidget(self.permisos_usuario, 1, 0, 1, 1)
        self.eliminar_usuario = QtGui.QPushButton(self.groupBox_3)
        self.eliminar_usuario.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.eliminar_usuario.setFont(font)
        self.eliminar_usuario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.eliminar_usuario.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/trash_user_postgresql.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eliminar_usuario.setIcon(icon3)
        self.eliminar_usuario.setIconSize(QtCore.QSize(38, 38))
        self.eliminar_usuario.setObjectName(_fromUtf8("eliminar_usuario"))
        self.gridLayout_2.addWidget(self.eliminar_usuario, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mui_adminempresas = QtGui.QPushButton(self.groupBox_2)
        self.mui_adminempresas.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mui_adminempresas.setFont(font)
        self.mui_adminempresas.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mui_adminempresas.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/manage_company.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_adminempresas.setIcon(icon4)
        self.mui_adminempresas.setIconSize(QtCore.QSize(32, 32))
        self.mui_adminempresas.setObjectName(_fromUtf8("mui_adminempresas"))
        self.gridLayout.addWidget(self.mui_adminempresas, 1, 0, 1, 1)
        self.eliminar_empresa = QtGui.QPushButton(self.groupBox_2)
        self.eliminar_empresa.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.eliminar_empresa.setFont(font)
        self.eliminar_empresa.setFocusPolicy(QtCore.Qt.NoFocus)
        self.eliminar_empresa.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/trash_company.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eliminar_empresa.setIcon(icon5)
        self.eliminar_empresa.setIconSize(QtCore.QSize(32, 32))
        self.eliminar_empresa.setObjectName(_fromUtf8("eliminar_empresa"))
        self.gridLayout.addWidget(self.eliminar_empresa, 1, 1, 1, 1)
        self.mui_restbackup = QtGui.QPushButton(self.groupBox_2)
        self.mui_restbackup.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mui_restbackup.setFont(font)
        self.mui_restbackup.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mui_restbackup.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/restore_database.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_restbackup.setIcon(icon6)
        self.mui_restbackup.setIconSize(QtCore.QSize(32, 32))
        self.mui_restbackup.setObjectName(_fromUtf8("mui_restbackup"))
        self.gridLayout.addWidget(self.mui_restbackup, 2, 1, 1, 1)
        self.mui_creabackup = QtGui.QPushButton(self.groupBox_2)
        self.mui_creabackup.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mui_creabackup.setFont(font)
        self.mui_creabackup.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mui_creabackup.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/backup_database.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_creabackup.setIcon(icon7)
        self.mui_creabackup.setIconSize(QtCore.QSize(32, 32))
        self.mui_creabackup.setObjectName(_fromUtf8("mui_creabackup"))
        self.gridLayout.addWidget(self.mui_creabackup, 2, 0, 1, 1)
        self.mui_crearbulmafact = QtGui.QPushButton(self.groupBox_2)
        self.mui_crearbulmafact.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mui_crearbulmafact.setFont(font)
        self.mui_crearbulmafact.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mui_crearbulmafact.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/iconbulmafact.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_crearbulmafact.setIcon(icon8)
        self.mui_crearbulmafact.setIconSize(QtCore.QSize(38, 38))
        self.mui_crearbulmafact.setObjectName(_fromUtf8("mui_crearbulmafact"))
        self.gridLayout.addWidget(self.mui_crearbulmafact, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(17, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mui_acerca = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mui_acerca.setFont(font)
        self.mui_acerca.setObjectName(_fromUtf8("mui_acerca"))
        self.horizontalLayout.addWidget(self.mui_acerca)
        spacerItem1 = QtGui.QSpacerItem(388, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.mui_salir = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mui_salir.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/bulmasetup_exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_salir.setIcon(icon9)
        self.mui_salir.setObjectName(_fromUtf8("mui_salir"))
        self.horizontalLayout.addWidget(self.mui_salir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.mui_salir, QtCore.SIGNAL(_fromUtf8("released()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BulmaSetup", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Gestión de Usuarios", None))
        self.nuevo_usuario.setText(_translate("MainWindow", "Nuevos Usuario de PostgreSQL", None))
        self.editar_usuario.setText(_translate("MainWindow", "Editar Usuarios de PostgreSQL", None))
        self.permisos_usuario.setText(_translate("MainWindow", "Modificar Permisos de PostgreSQL", None))
        self.eliminar_usuario.setText(_translate("MainWindow", "Eliminar Usuarios de PostgreSQL", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Gestión de Empresas", None))
        self.mui_adminempresas.setText(_translate("MainWindow", "Administrar Empresas Existentes", None))
        self.eliminar_empresa.setText(_translate("MainWindow", "Eliminar Empresas Existentes", None))
        self.mui_restbackup.setText(_translate("MainWindow", "Restaurar copia de seguridad", None))
        self.mui_creabackup.setText(_translate("MainWindow", "Crear Copia de Seguridad", None))
        self.mui_crearbulmafact.setText(_translate("MainWindow", "Crear Nueva Empresa", None))
        self.mui_acerca.setText(_translate("MainWindow", "Acerca de BulmaSetup", None))
        self.mui_salir.setText(_translate("MainWindow", "Salir", None))

import resources_rc
