# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestionusuariosbase.ui'
#
# Created: Wed May  6 17:11:19 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_GestionUsuarios(object):
    def setupUi(self, GestionUsuarios):
        GestionUsuarios.setObjectName("GestionUsuarios")
        GestionUsuarios.resize(224, 170)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GestionUsuarios.sizePolicy().hasHeightForWidth())
        GestionUsuarios.setSizePolicy(sizePolicy)
        GestionUsuarios.setMinimumSize(QtCore.QSize(224, 170))
        GestionUsuarios.setMaximumSize(QtCore.QSize(224, 170))
        GestionUsuarios.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/bulmasetup_usuario.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GestionUsuarios.setWindowIcon(icon)
        self.gridLayout_5 = QtGui.QGridLayout(GestionUsuarios)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.crear_usuario_postgres = QtGui.QPushButton(GestionUsuarios)
        self.crear_usuario_postgres.setMinimumSize(QtCore.QSize(180, 0))
        self.crear_usuario_postgres.setMaximumSize(QtCore.QSize(250, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/bulmasetup_nuevousuario.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.crear_usuario_postgres.setIcon(icon1)
        self.crear_usuario_postgres.setObjectName("crear_usuario_postgres")
        self.gridLayout.addWidget(self.crear_usuario_postgres, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(199, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 1, 0, 2, 2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        self.editar_usuario_postgres = QtGui.QPushButton(GestionUsuarios)
        self.editar_usuario_postgres.setMinimumSize(QtCore.QSize(180, 0))
        self.editar_usuario_postgres.setMaximumSize(QtCore.QSize(250, 16777215))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/bulmasetup_editarusuario.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editar_usuario_postgres.setIcon(icon2)
        self.editar_usuario_postgres.setObjectName("editar_usuario_postgres")
        self.gridLayout_2.addWidget(self.editar_usuario_postgres, 0, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 2, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(199, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 3, 0, 2, 2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 0, 1, 1)
        self.eliminar_usuario_postgres = QtGui.QPushButton(GestionUsuarios)
        self.eliminar_usuario_postgres.setMinimumSize(QtCore.QSize(180, 0))
        self.eliminar_usuario_postgres.setMaximumSize(QtCore.QSize(250, 16777215))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/bulmasetup_eliminarusuario.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eliminar_usuario_postgres.setIcon(icon3)
        self.eliminar_usuario_postgres.setObjectName("eliminar_usuario_postgres")
        self.gridLayout_3.addWidget(self.eliminar_usuario_postgres, 0, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 4, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(199, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem8, 5, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.mui_cancelar = QtGui.QPushButton(GestionUsuarios)
        self.mui_cancelar.setMinimumSize(QtCore.QSize(100, 0))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/bulmasetup_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_cancelar.setIcon(icon4)
        self.mui_cancelar.setObjectName("mui_cancelar")
        self.horizontalLayout.addWidget(self.mui_cancelar)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.gridLayout_4.addLayout(self.horizontalLayout, 6, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)

        self.retranslateUi(GestionUsuarios)
        QtCore.QObject.connect(self.mui_cancelar, QtCore.SIGNAL("released()"), GestionUsuarios.close)
        QtCore.QMetaObject.connectSlotsByName(GestionUsuarios)

    def retranslateUi(self, GestionUsuarios):
        GestionUsuarios.setWindowTitle(QtGui.QApplication.translate("GestionUsuarios", "Gestión de Usuarios", None, QtGui.QApplication.UnicodeUTF8))
        self.crear_usuario_postgres.setText(QtGui.QApplication.translate("GestionUsuarios", "Crear Usuario de PostgreSQL", None, QtGui.QApplication.UnicodeUTF8))
        self.editar_usuario_postgres.setText(QtGui.QApplication.translate("GestionUsuarios", "Editar Usuario de PostgreSQL", None, QtGui.QApplication.UnicodeUTF8))
        self.eliminar_usuario_postgres.setText(QtGui.QApplication.translate("GestionUsuarios", "Eliminar Usuarios de PostgreSQL", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_cancelar.setText(QtGui.QApplication.translate("GestionUsuarios", "Salir", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
