# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modificarusuariobase.ui'
#
# Created: Fri Apr 24 18:15:02 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ModificarUsuario(object):
    def setupUi(self, ModificarUsuario):
        ModificarUsuario.setObjectName("ModificarUsuario")
        ModificarUsuario.resize(649, 557)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/bulmasetup_editarusuario.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ModificarUsuario.setWindowIcon(icon)
        self.gridLayout_4 = QtGui.QGridLayout(ModificarUsuario)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtGui.QTabWidget(ModificarUsuario)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.listWidgetUser = QtGui.QListWidget(self.tab)
        self.listWidgetUser.setObjectName("listWidgetUser")
        self.gridLayout.addWidget(self.listWidgetUser, 1, 0, 1, 1)
        self.listWidgetDatabase = QtGui.QListWidget(self.tab)
        self.listWidgetDatabase.setObjectName("listWidgetDatabase")
        self.gridLayout.addWidget(self.listWidgetDatabase, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.listWidgetTable = QtGui.QListWidget(self.tab_3)
        self.listWidgetTable.setMaximumSize(QtCore.QSize(165000, 16777215))
        self.listWidgetTable.setObjectName("listWidgetTable")
        self.verticalLayout_3.addWidget(self.listWidgetTable)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.checkBox_create = QtGui.QCheckBox(self.groupBox)
        self.checkBox_create.setObjectName("checkBox_create")
        self.gridLayout_2.addWidget(self.checkBox_create, 1, 0, 1, 1)
        self.checkBox_temporary = QtGui.QCheckBox(self.groupBox)
        self.checkBox_temporary.setObjectName("checkBox_temporary")
        self.gridLayout_2.addWidget(self.checkBox_temporary, 1, 1, 1, 1)
        self.checkBox_dball = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.checkBox_dball.setFont(font)
        self.checkBox_dball.setObjectName("checkBox_dball")
        self.gridLayout_2.addWidget(self.checkBox_dball, 2, 0, 1, 1)
        self.checkBox_dbrevoke = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.checkBox_dbrevoke.setFont(font)
        self.checkBox_dbrevoke.setObjectName("checkBox_dbrevoke")
        self.gridLayout_2.addWidget(self.checkBox_dbrevoke, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 2)
        self.checkBox_select = QtGui.QCheckBox(self.groupBox)
        self.checkBox_select.setObjectName("checkBox_select")
        self.gridLayout_2.addWidget(self.checkBox_select, 4, 0, 1, 1)
        self.checkBox_insert = QtGui.QCheckBox(self.groupBox)
        self.checkBox_insert.setObjectName("checkBox_insert")
        self.gridLayout_2.addWidget(self.checkBox_insert, 4, 1, 1, 1)
        self.checkBox_update = QtGui.QCheckBox(self.groupBox)
        self.checkBox_update.setObjectName("checkBox_update")
        self.gridLayout_2.addWidget(self.checkBox_update, 5, 0, 1, 1)
        self.checkBox_delete = QtGui.QCheckBox(self.groupBox)
        self.checkBox_delete.setObjectName("checkBox_delete")
        self.gridLayout_2.addWidget(self.checkBox_delete, 5, 1, 1, 1)
        self.checkBox_trigger = QtGui.QCheckBox(self.groupBox)
        self.checkBox_trigger.setObjectName("checkBox_trigger")
        self.gridLayout_2.addWidget(self.checkBox_trigger, 6, 0, 1, 1)
        self.checkBox_references = QtGui.QCheckBox(self.groupBox)
        self.checkBox_references.setObjectName("checkBox_references")
        self.gridLayout_2.addWidget(self.checkBox_references, 6, 1, 1, 1)
        self.checkBox_all = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.checkBox_all.setFont(font)
        self.checkBox_all.setObjectName("checkBox_all")
        self.gridLayout_2.addWidget(self.checkBox_all, 7, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 236, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 8, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 1, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(389, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 2)
        self.mui_guardar = QtGui.QPushButton(self.tab_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/bulmasetup_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_guardar.setIcon(icon1)
        self.mui_guardar.setObjectName("mui_guardar")
        self.gridLayout_3.addWidget(self.mui_guardar, 1, 2, 1, 1)
        self.mui_salir = QtGui.QPushButton(self.tab_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/bulmasetup_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_salir.setIcon(icon2)
        self.mui_salir.setObjectName("mui_salir")
        self.gridLayout_3.addWidget(self.mui_salir, 1, 3, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mui_textBrowser = QtGui.QTextBrowser(self.tab_2)
        self.mui_textBrowser.setObjectName("mui_textBrowser")
        self.verticalLayout.addWidget(self.mui_textBrowser)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(ModificarUsuario)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.mui_salir, QtCore.SIGNAL("released()"), ModificarUsuario.close)
        QtCore.QMetaObject.connectSlotsByName(ModificarUsuario)

    def retranslateUi(self, ModificarUsuario):
        ModificarUsuario.setWindowTitle(QtGui.QApplication.translate("ModificarUsuario", "Modificar Permisos de Usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ModificarUsuario", "Selecciona un Usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ModificarUsuario", "Selecciona una Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("ModificarUsuario", "Usuario / Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ModificarUsuario", "Selecciona una Tabla", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ModificarUsuario", "Permisos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ModificarUsuario", "Selecciona permisos para la Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_create.setText(QtGui.QApplication.translate("ModificarUsuario", "CREATE", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_temporary.setText(QtGui.QApplication.translate("ModificarUsuario", "TEMPORARY", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_dball.setText(QtGui.QApplication.translate("ModificarUsuario", "GRANT ALL", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_dbrevoke.setText(QtGui.QApplication.translate("ModificarUsuario", "REVOKE ALL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ModificarUsuario", "Permisos para la tabla / tablas", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_select.setText(QtGui.QApplication.translate("ModificarUsuario", "SELECT", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_insert.setText(QtGui.QApplication.translate("ModificarUsuario", "INSERT", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_update.setText(QtGui.QApplication.translate("ModificarUsuario", "UPDATE", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_delete.setText(QtGui.QApplication.translate("ModificarUsuario", "DELETE", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_trigger.setText(QtGui.QApplication.translate("ModificarUsuario", "TRIGGER", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_references.setText(QtGui.QApplication.translate("ModificarUsuario", "REFERENCES", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_all.setText(QtGui.QApplication.translate("ModificarUsuario", "SELECCIONAR TODOS", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_guardar.setText(QtGui.QApplication.translate("ModificarUsuario", "Asignar Permisos", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_salir.setText(QtGui.QApplication.translate("ModificarUsuario", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("ModificarUsuario", "Permisos", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("ModificarUsuario", "Consola", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
