# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modificarcontabilidadbase.ui'
#
# Created: Tue Feb  8 17:13:41 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ModificarContabilidadBase(object):
    def setupUi(self, ModificarContabilidadBase):
        ModificarContabilidadBase.setObjectName(_fromUtf8("ModificarContabilidadBase"))
        ModificarContabilidadBase.resize(875, 608)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ModificarContabilidadBase.sizePolicy().hasHeightForWidth())
        ModificarContabilidadBase.setSizePolicy(sizePolicy)
        ModificarContabilidadBase.setMaximumSize(QtCore.QSize(2800, 2500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/iconbulmacont.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ModificarContabilidadBase.setWindowIcon(icon)
        self.verticalLayout_3 = QtGui.QVBoxLayout(ModificarContabilidadBase)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.groupBox = QtGui.QGroupBox(ModificarContabilidadBase)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.mui_categoria = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mui_categoria.sizePolicy().hasHeightForWidth())
        self.mui_categoria.setSizePolicy(sizePolicy)
        self.mui_categoria.setObjectName(_fromUtf8("mui_categoria"))
        self.horizontalLayout.addWidget(self.mui_categoria)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(43, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.mui_vertodos = QtGui.QCheckBox(ModificarContabilidadBase)
        self.mui_vertodos.setObjectName(_fromUtf8("mui_vertodos"))
        self.verticalLayout_2.addWidget(self.mui_vertodos)
        self.tabWidget = QtGui.QTabWidget(ModificarContabilidadBase)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.mui_nomempresa = QtGui.QLineEdit(self.tab_2)
        self.mui_nomempresa.setObjectName(_fromUtf8("mui_nomempresa"))
        self.gridLayout_3.addWidget(self.mui_nomempresa, 0, 2, 1, 2)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 2)
        self.mui_nomdb = QtGui.QLineEdit(self.tab_2)
        self.mui_nomdb.setReadOnly(True)
        self.mui_nomdb.setObjectName(_fromUtf8("mui_nomdb"))
        self.gridLayout_3.addWidget(self.mui_nomdb, 1, 2, 1, 2)
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 2)
        self.mui_databaserevision = QtGui.QLineEdit(self.tab_2)
        self.mui_databaserevision.setReadOnly(True)
        self.mui_databaserevision.setObjectName(_fromUtf8("mui_databaserevision"))
        self.gridLayout_3.addWidget(self.mui_databaserevision, 2, 2, 1, 2)
        self.mui_actualizarDB = QtGui.QCheckBox(self.tab_2)
        self.mui_actualizarDB.setChecked(False)
        self.mui_actualizarDB.setObjectName(_fromUtf8("mui_actualizarDB"))
        self.gridLayout_3.addWidget(self.mui_actualizarDB, 3, 3, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mui_img = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mui_img.sizePolicy().hasHeightForWidth())
        self.mui_img.setSizePolicy(sizePolicy)
        self.mui_img.setMaximumSize(QtCore.QSize(400, 150))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.mui_img.setPalette(palette)
        self.mui_img.setAutoFillBackground(True)
        self.mui_img.setText(_fromUtf8(""))
        self.mui_img.setObjectName(_fromUtf8("mui_img"))
        self.gridLayout_2.addWidget(self.mui_img, 1, 0, 1, 1)
        self.mui_textfile = QtGui.QLineEdit(self.tab_2)
        self.mui_textfile.setObjectName(_fromUtf8("mui_textfile"))
        self.gridLayout_2.addWidget(self.mui_textfile, 2, 0, 1, 1)
        self.mui_chosefile = QtGui.QPushButton(self.tab_2)
        self.mui_chosefile.setObjectName(_fromUtf8("mui_chosefile"))
        self.gridLayout_2.addWidget(self.mui_chosefile, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 4, 0, 1, 4)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.vboxlayout = QtGui.QVBoxLayout(self.tab)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.mui_plugins = QtGui.QTableWidget(self.tab)
        self.mui_plugins.setAlternatingRowColors(True)
        self.mui_plugins.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.mui_plugins.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.mui_plugins.setGridStyle(QtCore.Qt.NoPen)
        self.mui_plugins.setObjectName(_fromUtf8("mui_plugins"))
        self.mui_plugins.setColumnCount(3)
        self.mui_plugins.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins.setHorizontalHeaderItem(2, item)
        self.vboxlayout.addWidget(self.mui_plugins)
        self.tabWidget.addTab(self.tab, icon, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mui_textBrowser = QtGui.QTextBrowser(self.tab_3)
        self.mui_textBrowser.setObjectName(_fromUtf8("mui_textBrowser"))
        self.verticalLayout.addWidget(self.mui_textBrowser)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/terminal.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon1, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.toolButton = QtGui.QToolButton(ModificarContabilidadBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMaximumSize(QtCore.QSize(15, 16777215))
        self.toolButton.setCheckable(True)
        self.toolButton.setChecked(True)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_4.addWidget(self.toolButton)
        self.mui_descripcion = QtGui.QTextBrowser(ModificarContabilidadBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mui_descripcion.sizePolicy().hasHeightForWidth())
        self.mui_descripcion.setSizePolicy(sizePolicy)
        self.mui_descripcion.setMinimumSize(QtCore.QSize(350, 0))
        self.mui_descripcion.setMaximumSize(QtCore.QSize(350, 16777215))
        self.mui_descripcion.setObjectName(_fromUtf8("mui_descripcion"))
        self.horizontalLayout_4.addWidget(self.mui_descripcion)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.mui_aceptar = QtGui.QPushButton(ModificarContabilidadBase)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/bulmasetup_aceptar.xpm")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_aceptar.setIcon(icon2)
        self.mui_aceptar.setObjectName(_fromUtf8("mui_aceptar"))
        self.horizontalLayout_3.addWidget(self.mui_aceptar)
        self.mui_permisos = QtGui.QPushButton(ModificarContabilidadBase)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/bulmasetup_editarusuario.xpm")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_permisos.setIcon(icon3)
        self.mui_permisos.setObjectName(_fromUtf8("mui_permisos"))
        self.horizontalLayout_3.addWidget(self.mui_permisos)
        self.mui_hacerbackup = QtGui.QPushButton(ModificarContabilidadBase)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/backup_database.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_hacerbackup.setIcon(icon4)
        self.mui_hacerbackup.setObjectName(_fromUtf8("mui_hacerbackup"))
        self.horizontalLayout_3.addWidget(self.mui_hacerbackup)
        self.mui_cancelar = QtGui.QPushButton(ModificarContabilidadBase)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/bulmasetup_exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_cancelar.setIcon(icon5)
        self.mui_cancelar.setObjectName(_fromUtf8("mui_cancelar"))
        self.horizontalLayout_3.addWidget(self.mui_cancelar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_5.setBuddy(self.mui_categoria)
        self.label.setBuddy(self.mui_nomempresa)
        self.label_2.setBuddy(self.mui_nomdb)

        self.retranslateUi(ModificarContabilidadBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.mui_cancelar, QtCore.SIGNAL(_fromUtf8("released()")), ModificarContabilidadBase.reject)
        QtCore.QObject.connect(self.toolButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.mui_descripcion.setHidden)
        QtCore.QMetaObject.connectSlotsByName(ModificarContabilidadBase)

    def retranslateUi(self, ModificarContabilidadBase):
        ModificarContabilidadBase.setWindowTitle(QtGui.QApplication.translate("ModificarContabilidadBase", "Contabilidad", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ModificarContabilidadBase", "Opciones de Filtrado de Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Categoria ", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_vertodos.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Mostrar todos los plugins o solo los instalados", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Nombre Empresa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Nombre Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Version de la Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_actualizarDB.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Actualizar Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_chosefile.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Logotipo de la empresa", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("ModificarContabilidadBase", "Propiedades Empresa", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins.setSortingEnabled(True)
        self.mui_plugins.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Descripcion", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Version Instalada", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("ModificarContabilidadBase", "Plugins BulmaCont", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("ModificarContabilidadBase", "Consola", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_aceptar.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Aplicar cambios", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_permisos.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Administrar Permisos", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_hacerbackup.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Hacer copia de seguridad", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_cancelar.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Cerrar", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
