# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modificarusuariobase.ui'
#
# Created: Fri Apr 24 17:37:24 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ModificarUsuario(object):
    def setupUi(self, ModificarUsuario):
        ModificarUsuario.setObjectName("ModificarUsuario")
        ModificarUsuario.resize(943, 435)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/bulmasetup_editarusuario.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ModificarUsuario.setWindowIcon(icon)
        self.label = QtGui.QLabel(ModificarUsuario)
        self.label.setGeometry(QtCore.QRect(70, 9, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(ModificarUsuario)
        self.label_2.setGeometry(QtCore.QRect(300, 9, 221, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtGui.QLabel(ModificarUsuario)
        self.label_5.setGeometry(QtCore.QRect(730, 9, 271, 19))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.listWidgetUser = QtGui.QListWidget(ModificarUsuario)
        self.listWidgetUser.setGeometry(QtCore.QRect(9, 28, 235, 241))
        self.listWidgetUser.setObjectName("listWidgetUser")
        self.listWidgetDatabase = QtGui.QListWidget(ModificarUsuario)
        self.listWidgetDatabase.setGeometry(QtCore.QRect(250, 28, 235, 241))
        self.listWidgetDatabase.setObjectName("listWidgetDatabase")
        self.listWidgetTable = QtGui.QListWidget(ModificarUsuario)
        self.listWidgetTable.setGeometry(QtCore.QRect(491, 28, 214, 401))
        self.listWidgetTable.setObjectName("listWidgetTable")
        self.checkBox_dball = QtGui.QCheckBox(ModificarUsuario)
        self.checkBox_dball.setGeometry(QtCore.QRect(725, 60, 76, 19))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.checkBox_dball.setFont(font)
        self.checkBox_dball.setObjectName("checkBox_dball")
        self.checkBox_dbrevoke = QtGui.QCheckBox(ModificarUsuario)
        self.checkBox_dbrevoke.setGeometry(QtCore.QRect(836, 60, 98, 19))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.checkBox_dbrevoke.setFont(font)
        self.checkBox_dbrevoke.setObjectName("checkBox_dbrevoke")
        self.checkBox_create = QtGui.QCheckBox(ModificarUsuario)
        self.checkBox_create.setGeometry(QtCore.QRect(725, 100, 76, 19))
        self.checkBox_create.setObjectName("checkBox_create")
        self.checkBox_temporary = QtGui.QCheckBox(ModificarUsuario)
        self.checkBox_temporary.setGeometry(QtCore.QRect(836, 100, 98, 19))
        self.checkBox_temporary.setObjectName("checkBox_temporary")
        self.label_4 = QtGui.QLabel(ModificarUsuario)
        self.label_4.setGeometry(QtCore.QRect(750, 160, 191, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.checkBox_select = QtGui.QCheckBox(ModificarUsuario)
        self.checkBox_select.setGeometry(QtCore.QRect(725, 205, 76, 19))
        self.checkBox_select.setObjectName("checkBox_select")
        self.checkBox_insert = QtGui.QCheckBox(ModificarUsuario)
        self.checkBox_insert.setGeometry(QtCore.QRect(836, 205, 98, 19))
        self.checkBox_insert.setObjectName("checkBox_insert")
        self.checkBox_update = QtGui.QCheckBox(ModificarUsuario)
        self.checkBox_update.setGeometry(QtCore.QRect(725, 230, 76, 19))
        self.checkBox_update.setObjectName("checkBox_update")
        self.checkBox_delete = QtGui.QCheckBox(ModificarUsuario)
        self.checkBox_delete.setGeometry(QtCore.QRect(836, 230, 98, 19))
        self.checkBox_delete.setObjectName("checkBox_delete")
        self.checkBox_trigger = QtGui.QCheckBox(ModificarUsuario)
        self.checkBox_trigger.setGeometry(QtCore.QRect(725, 255, 76, 19))
        self.checkBox_trigger.setObjectName("checkBox_trigger")
        self.checkBox_references = QtGui.QCheckBox(ModificarUsuario)
        self.checkBox_references.setGeometry(QtCore.QRect(836, 255, 98, 19))
        self.checkBox_references.setObjectName("checkBox_references")
        self.checkBox_all = QtGui.QCheckBox(ModificarUsuario)
        self.checkBox_all.setGeometry(QtCore.QRect(770, 310, 103, 19))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.checkBox_all.setFont(font)
        self.checkBox_all.setObjectName("checkBox_all")
        self.mui_guardar = QtGui.QPushButton(ModificarUsuario)
        self.mui_guardar.setGeometry(QtCore.QRect(744, 380, 76, 24))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/bulmasetup_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_guardar.setIcon(icon1)
        self.mui_guardar.setObjectName("mui_guardar")
        self.mui_salir = QtGui.QPushButton(ModificarUsuario)
        self.mui_salir.setGeometry(QtCore.QRect(830, 380, 81, 24))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/bulmasetup_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_salir.setIcon(icon2)
        self.mui_salir.setObjectName("mui_salir")
        self.mui_textBrowser = QtGui.QTextBrowser(ModificarUsuario)
        self.mui_textBrowser.setGeometry(QtCore.QRect(9, 298, 476, 131))
        self.mui_textBrowser.setObjectName("mui_textBrowser")
        self.label_3 = QtGui.QLabel(ModificarUsuario)
        self.label_3.setGeometry(QtCore.QRect(550, 9, 104, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtGui.QLabel(ModificarUsuario)
        self.label_6.setGeometry(QtCore.QRect(200, 280, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(ModificarUsuario)
        QtCore.QObject.connect(self.mui_salir, QtCore.SIGNAL("released()"), ModificarUsuario.close)
        QtCore.QMetaObject.connectSlotsByName(ModificarUsuario)

    def retranslateUi(self, ModificarUsuario):
        ModificarUsuario.setWindowTitle(QtGui.QApplication.translate("ModificarUsuario", "Modificar Permisos de Usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ModificarUsuario", "Selecciona un Usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ModificarUsuario", "Selecciona una Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ModificarUsuario", "Selecciona permisos para la Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_dball.setText(QtGui.QApplication.translate("ModificarUsuario", "GRANT ALL", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_dbrevoke.setText(QtGui.QApplication.translate("ModificarUsuario", "REVOKE ALL", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_create.setText(QtGui.QApplication.translate("ModificarUsuario", "CREATE", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_temporary.setText(QtGui.QApplication.translate("ModificarUsuario", "TEMPORARY", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ModificarUsuario", "Selecciona permisos para la Tabla", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_select.setText(QtGui.QApplication.translate("ModificarUsuario", "SELECT", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_insert.setText(QtGui.QApplication.translate("ModificarUsuario", "INSERT", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_update.setText(QtGui.QApplication.translate("ModificarUsuario", "UPDATE", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_delete.setText(QtGui.QApplication.translate("ModificarUsuario", "DELETE", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_trigger.setText(QtGui.QApplication.translate("ModificarUsuario", "TRIGGER", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_references.setText(QtGui.QApplication.translate("ModificarUsuario", "REFERENCES", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_all.setText(QtGui.QApplication.translate("ModificarUsuario", "MARCAR TODOS", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_guardar.setText(QtGui.QApplication.translate("ModificarUsuario", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_salir.setText(QtGui.QApplication.translate("ModificarUsuario", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ModificarUsuario", "Selecciona una Tabla", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ModificarUsuario", "Historial de Comandos", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
