# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modificarcontabilidadbase.ui'
#
# Created: Thu May 14 23:24:22 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ModificarContabilidadBase(object):
    def setupUi(self, ModificarContabilidadBase):
        ModificarContabilidadBase.setObjectName("ModificarContabilidadBase")
        ModificarContabilidadBase.resize(852, 608)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ModificarContabilidadBase.sizePolicy().hasHeightForWidth())
        ModificarContabilidadBase.setSizePolicy(sizePolicy)
        ModificarContabilidadBase.setMaximumSize(QtCore.QSize(2800, 2500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/iconbulmacont.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ModificarContabilidadBase.setWindowIcon(icon)
        self.verticalLayout_3 = QtGui.QVBoxLayout(ModificarContabilidadBase)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(ModificarContabilidadBase)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.mui_nomempresa = QtGui.QLineEdit(ModificarContabilidadBase)
        self.mui_nomempresa.setObjectName("mui_nomempresa")
        self.gridLayout.addWidget(self.mui_nomempresa, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(ModificarContabilidadBase)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.mui_nomdb = QtGui.QLineEdit(ModificarContabilidadBase)
        self.mui_nomdb.setReadOnly(True)
        self.mui_nomdb.setObjectName("mui_nomdb")
        self.gridLayout.addWidget(self.mui_nomdb, 1, 1, 1, 1)
        self.mui_actualizarDB = QtGui.QCheckBox(ModificarContabilidadBase)
        self.mui_actualizarDB.setChecked(False)
        self.mui_actualizarDB.setObjectName("mui_actualizarDB")
        self.gridLayout.addWidget(self.mui_actualizarDB, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(ModificarContabilidadBase)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.mui_databaserevision = QtGui.QLineEdit(ModificarContabilidadBase)
        self.mui_databaserevision.setReadOnly(True)
        self.mui_databaserevision.setObjectName("mui_databaserevision")
        self.gridLayout.addWidget(self.mui_databaserevision, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.groupBox = QtGui.QGroupBox(ModificarContabilidadBase)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mui_vertodos = QtGui.QCheckBox(self.groupBox)
        self.mui_vertodos.setObjectName("mui_vertodos")
        self.horizontalLayout_2.addWidget(self.mui_vertodos)
        spacerItem = QtGui.QSpacerItem(43, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.mui_categoria = QtGui.QComboBox(self.groupBox)
        self.mui_categoria.setObjectName("mui_categoria")
        self.horizontalLayout.addWidget(self.mui_categoria)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.tabWidget = QtGui.QTabWidget(ModificarContabilidadBase)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.vboxlayout = QtGui.QVBoxLayout(self.tab)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.mui_plugins = QtGui.QTableWidget(self.tab)
        self.mui_plugins.setAlternatingRowColors(True)
        self.mui_plugins.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.mui_plugins.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.mui_plugins.setGridStyle(QtCore.Qt.NoPen)
        self.mui_plugins.setObjectName("mui_plugins")
        self.mui_plugins.setColumnCount(3)
        self.mui_plugins.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins.setHorizontalHeaderItem(2, item)
        self.vboxlayout.addWidget(self.mui_plugins)
        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mui_textBrowser = QtGui.QTextBrowser(self.tab_3)
        self.mui_textBrowser.setObjectName("mui_textBrowser")
        self.verticalLayout.addWidget(self.mui_textBrowser)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/terminal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon1, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.toolButton = QtGui.QToolButton(ModificarContabilidadBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMaximumSize(QtCore.QSize(15, 16777215))
        self.toolButton.setCheckable(True)
        self.toolButton.setChecked(True)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_4.addWidget(self.toolButton)
        self.mui_descripcion = QtGui.QTextBrowser(ModificarContabilidadBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mui_descripcion.sizePolicy().hasHeightForWidth())
        self.mui_descripcion.setSizePolicy(sizePolicy)
        self.mui_descripcion.setMinimumSize(QtCore.QSize(350, 0))
        self.mui_descripcion.setMaximumSize(QtCore.QSize(350, 16777215))
        self.mui_descripcion.setObjectName("mui_descripcion")
        self.horizontalLayout_4.addWidget(self.mui_descripcion)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mui_aceptar = QtGui.QPushButton(ModificarContabilidadBase)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/bulmasetup_aceptar.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_aceptar.setIcon(icon2)
        self.mui_aceptar.setObjectName("mui_aceptar")
        self.horizontalLayout_3.addWidget(self.mui_aceptar)
        self.mui_permisos = QtGui.QPushButton(ModificarContabilidadBase)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/bulmasetup_editarusuario.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_permisos.setIcon(icon3)
        self.mui_permisos.setObjectName("mui_permisos")
        self.horizontalLayout_3.addWidget(self.mui_permisos)
        self.mui_hacerbackup = QtGui.QPushButton(ModificarContabilidadBase)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/bulmasetup_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_hacerbackup.setIcon(icon4)
        self.mui_hacerbackup.setObjectName("mui_hacerbackup")
        self.horizontalLayout_3.addWidget(self.mui_hacerbackup)
        self.mui_cancelar = QtGui.QPushButton(ModificarContabilidadBase)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/bulmasetup_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mui_cancelar.setIcon(icon5)
        self.mui_cancelar.setObjectName("mui_cancelar")
        self.horizontalLayout_3.addWidget(self.mui_cancelar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label.setBuddy(self.mui_nomempresa)
        self.label_2.setBuddy(self.mui_nomdb)
        self.label_5.setBuddy(self.mui_categoria)

        self.retranslateUi(ModificarContabilidadBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.mui_cancelar, QtCore.SIGNAL("released()"), ModificarContabilidadBase.reject)
        QtCore.QObject.connect(self.toolButton, QtCore.SIGNAL("toggled(bool)"), self.mui_descripcion.setHidden)
        QtCore.QMetaObject.connectSlotsByName(ModificarContabilidadBase)

    def retranslateUi(self, ModificarContabilidadBase):
        ModificarContabilidadBase.setWindowTitle(QtGui.QApplication.translate("ModificarContabilidadBase", "Contabilidad", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Nombre Empresa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Nombre Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_actualizarDB.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Actualizar Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Version de la Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ModificarContabilidadBase", "Opciones de Filtrado de Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_vertodos.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Mostrar todos los plugins o solo los instalados", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Categoria ", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Descripcion", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Version Instalada", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("ModificarContabilidadBase", "Plugins BulmaCont", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("ModificarContabilidadBase", "Consola", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_aceptar.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Aplicar cambios", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_permisos.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Administrar Permisos", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_hacerbackup.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Hacer copia de seguridad", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_cancelar.setText(QtGui.QApplication.translate("ModificarContabilidadBase", "Cerrar", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
