# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modificarfacturacionbase.ui'
#
# Created: Thu Feb 26 18:53:56 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ModificarFacturacionBase(object):
    def setupUi(self, ModificarFacturacionBase):
        ModificarFacturacionBase.setObjectName("ModificarFacturacionBase")
        ModificarFacturacionBase.resize(800, 608)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ModificarFacturacionBase.sizePolicy().hasHeightForWidth())
        ModificarFacturacionBase.setSizePolicy(sizePolicy)
        ModificarFacturacionBase.setMaximumSize(QtCore.QSize(800, 608))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../.designer/images/png/bulmafact.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ModificarFacturacionBase.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(ModificarFacturacionBase)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(ModificarFacturacionBase)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.mui_nomempresa = QtGui.QLineEdit(ModificarFacturacionBase)
        self.mui_nomempresa.setObjectName("mui_nomempresa")
        self.gridLayout.addWidget(self.mui_nomempresa, 0, 1, 1, 3)
        self.mui_descripcion = QtGui.QTextBrowser(ModificarFacturacionBase)
        self.mui_descripcion.setObjectName("mui_descripcion")
        self.gridLayout.addWidget(self.mui_descripcion, 0, 4, 5, 1)
        self.label_2 = QtGui.QLabel(ModificarFacturacionBase)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.mui_nomdb = QtGui.QLineEdit(ModificarFacturacionBase)
        self.mui_nomdb.setReadOnly(True)
        self.mui_nomdb.setObjectName("mui_nomdb")
        self.gridLayout.addWidget(self.mui_nomdb, 1, 1, 1, 2)
        self.mui_actualizarDB = QtGui.QCheckBox(ModificarFacturacionBase)
        self.mui_actualizarDB.setChecked(False)
        self.mui_actualizarDB.setObjectName("mui_actualizarDB")
        self.gridLayout.addWidget(self.mui_actualizarDB, 1, 3, 1, 1)
        self.label_3 = QtGui.QLabel(ModificarFacturacionBase)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.mui_databaserevision = QtGui.QLineEdit(ModificarFacturacionBase)
        self.mui_databaserevision.setReadOnly(True)
        self.mui_databaserevision.setObjectName("mui_databaserevision")
        self.gridLayout.addWidget(self.mui_databaserevision, 2, 1, 1, 2)
        self.mui_soporteTPV = QtGui.QCheckBox(ModificarFacturacionBase)
        self.mui_soporteTPV.setChecked(False)
        self.mui_soporteTPV.setObjectName("mui_soporteTPV")
        self.gridLayout.addWidget(self.mui_soporteTPV, 2, 3, 1, 1)
        self.groupBox = QtGui.QGroupBox(ModificarFacturacionBase)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mui_vertodos = QtGui.QCheckBox(self.groupBox)
        self.mui_vertodos.setObjectName("mui_vertodos")
        self.horizontalLayout_2.addWidget(self.mui_vertodos)
        spacerItem = QtGui.QSpacerItem(43, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.mui_categoria = QtGui.QComboBox(self.groupBox)
        self.mui_categoria.setObjectName("mui_categoria")
        self.mui_categoria.addItem(QtCore.QString())
        self.mui_categoria.addItem(QtCore.QString())
        self.mui_categoria.addItem(QtCore.QString())
        self.mui_categoria.addItem(QtCore.QString())
        self.mui_categoria.addItem(QtCore.QString())
        self.mui_categoria.addItem(QtCore.QString())
        self.horizontalLayout.addWidget(self.mui_categoria)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 4)
        self.tabWidget = QtGui.QTabWidget(ModificarFacturacionBase)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.vboxlayout = QtGui.QVBoxLayout(self.tab)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.mui_plugins = QtGui.QTableWidget(self.tab)
        self.mui_plugins.setAlternatingRowColors(True)
        self.mui_plugins.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.mui_plugins.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.mui_plugins.setGridStyle(QtCore.Qt.NoPen)
        self.mui_plugins.setObjectName("mui_plugins")
        self.mui_plugins.setColumnCount(3)
        self.mui_plugins.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins.setHorizontalHeaderItem(2, item)
        self.vboxlayout.addWidget(self.mui_plugins)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.tab_2)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.mui_plugins1 = QtGui.QTableWidget(self.tab_2)
        self.mui_plugins1.setAlternatingRowColors(True)
        self.mui_plugins1.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.mui_plugins1.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.mui_plugins1.setGridStyle(QtCore.Qt.NoPen)
        self.mui_plugins1.setObjectName("mui_plugins1")
        self.mui_plugins1.setColumnCount(3)
        self.mui_plugins1.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins1.setHorizontalHeaderItem(2, item)
        self.vboxlayout1.addWidget(self.mui_plugins1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mui_textBrowser = QtGui.QTextBrowser(self.tab_3)
        self.mui_textBrowser.setObjectName("mui_textBrowser")
        self.verticalLayout.addWidget(self.mui_textBrowser)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 4, 0, 1, 4)
        self.mui_aceptar = QtGui.QPushButton(ModificarFacturacionBase)
        self.mui_aceptar.setObjectName("mui_aceptar")
        self.gridLayout.addWidget(self.mui_aceptar, 5, 0, 1, 2)
        self.mui_hacerbackup = QtGui.QPushButton(ModificarFacturacionBase)
        self.mui_hacerbackup.setObjectName("mui_hacerbackup")
        self.gridLayout.addWidget(self.mui_hacerbackup, 5, 2, 1, 2)
        self.mui_cancelar = QtGui.QPushButton(ModificarFacturacionBase)
        self.mui_cancelar.setObjectName("mui_cancelar")
        self.gridLayout.addWidget(self.mui_cancelar, 5, 4, 1, 1)
        self.label.setBuddy(self.mui_nomempresa)
        self.label_2.setBuddy(self.mui_nomdb)
        self.label_5.setBuddy(self.mui_categoria)

        self.retranslateUi(ModificarFacturacionBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.mui_cancelar, QtCore.SIGNAL("released()"), ModificarFacturacionBase.reject)
        QtCore.QObject.connect(self.mui_soporteTPV, QtCore.SIGNAL("toggled(bool)"), self.mui_plugins1.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ModificarFacturacionBase)

    def retranslateUi(self, ModificarFacturacionBase):
        ModificarFacturacionBase.setWindowTitle(QtGui.QApplication.translate("ModificarFacturacionBase", "Nueva Facturacion", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Nombre Empresa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Nombre Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_actualizarDB.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Actualizar Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Version de la Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_soporteTPV.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Instalar Soporte para TPV en esta empresa", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ModificarFacturacionBase", "Opciones de Filtrado de Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_vertodos.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Mostrar todos los plugins o solo los instalados", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Categoria", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_categoria.setItemText(0, QtGui.QApplication.translate("ModificarFacturacionBase", "Todas las Categorias", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_categoria.setItemText(1, QtGui.QApplication.translate("ModificarFacturacionBase", "Facturacion Generica", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_categoria.setItemText(2, QtGui.QApplication.translate("ModificarFacturacionBase", "Asociaciones de Padres de Alumnos", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_categoria.setItemText(3, QtGui.QApplication.translate("ModificarFacturacionBase", "Fabricacion y Trazabilidad", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_categoria.setItemText(4, QtGui.QApplication.translate("ModificarFacturacionBase", "IVA. Incluido", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_categoria.setItemText(5, QtGui.QApplication.translate("ModificarFacturacionBase", "Utilidades Genericas", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Descripcion", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Version Instalada", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("ModificarFacturacionBase", "Plugins BulmaFact", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins1.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins1.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Descripcion", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins1.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Version Instalada", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("ModificarFacturacionBase", "Plugins BulmaTPV", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("ModificarFacturacionBase", "Consola", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_aceptar.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Aplicar cambios", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_hacerbackup.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Hacer copia de seguridad", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_cancelar.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Cerrar", None, QtGui.QApplication.UnicodeUTF8))

