# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modificarfacturacionbase.ui'
#
# Created: Sat Feb 21 14:45:00 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ModificarFacturacionBase(object):
    def setupUi(self, ModificarFacturacionBase):
        ModificarFacturacionBase.setObjectName("ModificarFacturacionBase")
        ModificarFacturacionBase.resize(800, 608)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ModificarFacturacionBase.sizePolicy().hasHeightForWidth())
        ModificarFacturacionBase.setSizePolicy(sizePolicy)
        ModificarFacturacionBase.setMaximumSize(QtCore.QSize(800, 608))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../.designer/images/png/bulmafact.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ModificarFacturacionBase.setWindowIcon(icon)
        self.label = QtGui.QLabel(ModificarFacturacionBase)
        self.label.setGeometry(QtCore.QRect(4, 4, 73, 24))
        self.label.setObjectName("label")
        self.mui_nomempresa = QtGui.QLineEdit(ModificarFacturacionBase)
        self.mui_nomempresa.setGeometry(QtCore.QRect(81, 4, 385, 24))
        self.mui_nomempresa.setObjectName("mui_nomempresa")
        self.label_2 = QtGui.QLabel(ModificarFacturacionBase)
        self.label_2.setGeometry(QtCore.QRect(470, 4, 98, 24))
        self.label_2.setObjectName("label_2")
        self.mui_nomdb = QtGui.QLineEdit(ModificarFacturacionBase)
        self.mui_nomdb.setGeometry(QtCore.QRect(572, 4, 224, 24))
        self.mui_nomdb.setReadOnly(True)
        self.mui_nomdb.setObjectName("mui_nomdb")
        self.label_3 = QtGui.QLabel(ModificarFacturacionBase)
        self.label_3.setGeometry(QtCore.QRect(4, 32, 138, 24))
        self.label_3.setObjectName("label_3")
        self.mui_databaserevision = QtGui.QLineEdit(ModificarFacturacionBase)
        self.mui_databaserevision.setGeometry(QtCore.QRect(242, 32, 224, 24))
        self.mui_databaserevision.setReadOnly(True)
        self.mui_databaserevision.setObjectName("mui_databaserevision")
        self.mui_soporteTPV = QtGui.QCheckBox(ModificarFacturacionBase)
        self.mui_soporteTPV.setGeometry(QtCore.QRect(470, 32, 326, 23))
        self.mui_soporteTPV.setChecked(False)
        self.mui_soporteTPV.setObjectName("mui_soporteTPV")
        self.label_4 = QtGui.QLabel(ModificarFacturacionBase)
        self.label_4.setGeometry(QtCore.QRect(4, 60, 462, 16))
        self.label_4.setObjectName("label_4")
        self.mui_vertodos = QtGui.QCheckBox(ModificarFacturacionBase)
        self.mui_vertodos.setGeometry(QtCore.QRect(4, 78, 462, 23))
        self.mui_vertodos.setObjectName("mui_vertodos")
        self.mui_categoria = QtGui.QComboBox(ModificarFacturacionBase)
        self.mui_categoria.setGeometry(QtCore.QRect(81, 105, 385, 24))
        self.mui_categoria.setObjectName("mui_categoria")
        self.mui_categoria.addItem(QtCore.QString())
        self.mui_categoria.addItem(QtCore.QString())
        self.mui_categoria.addItem(QtCore.QString())
        self.mui_categoria.addItem(QtCore.QString())
        self.mui_categoria.addItem(QtCore.QString())
        self.mui_categoria.addItem(QtCore.QString())
        self.tabWidget = QtGui.QTabWidget(ModificarFacturacionBase)
        self.tabWidget.setGeometry(QtCore.QRect(4, 133, 792, 444))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.vboxlayout = QtGui.QVBoxLayout(self.tab)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.mui_plugins = QtGui.QTableWidget(self.tab)
        self.mui_plugins.setAlternatingRowColors(True)
        self.mui_plugins.setObjectName("mui_plugins")
        self.mui_plugins.setColumnCount(3)
        self.mui_plugins.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins.setHorizontalHeaderItem(2, item)
        self.vboxlayout.addWidget(self.mui_plugins)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.tab_2)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.mui_plugins1 = QtGui.QTableWidget(self.tab_2)
        self.mui_plugins1.setAlternatingRowColors(True)
        self.mui_plugins1.setObjectName("mui_plugins1")
        self.mui_plugins1.setColumnCount(3)
        self.mui_plugins1.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.mui_plugins1.setHorizontalHeaderItem(2, item)
        self.vboxlayout1.addWidget(self.mui_plugins1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mui_textBrowser = QtGui.QTextBrowser(self.tab_3)
        self.mui_textBrowser.setObjectName("mui_textBrowser")
        self.verticalLayout.addWidget(self.mui_textBrowser)
        self.tabWidget.addTab(self.tab_3, "")
        self.mui_actualizardatabase = QtGui.QPushButton(ModificarFacturacionBase)
        self.mui_actualizardatabase.setGeometry(QtCore.QRect(4, 581, 138, 23))
        self.mui_actualizardatabase.setObjectName("mui_actualizardatabase")
        self.mui_aceptar = QtGui.QPushButton(ModificarFacturacionBase)
        self.mui_aceptar.setGeometry(QtCore.QRect(146, 581, 92, 23))
        self.mui_aceptar.setObjectName("mui_aceptar")
        self.mui_hacerbackup = QtGui.QPushButton(ModificarFacturacionBase)
        self.mui_hacerbackup.setGeometry(QtCore.QRect(242, 581, 224, 23))
        self.mui_hacerbackup.setObjectName("mui_hacerbackup")
        self.mui_cancelar = QtGui.QPushButton(ModificarFacturacionBase)
        self.mui_cancelar.setGeometry(QtCore.QRect(572, 581, 224, 23))
        self.mui_cancelar.setObjectName("mui_cancelar")
        self.label_5 = QtGui.QLabel(ModificarFacturacionBase)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 41, 14))
        self.label_5.setObjectName("label_5")
        self.label.setBuddy(self.mui_nomempresa)
        self.label_2.setBuddy(self.mui_nomdb)
        self.label_5.setBuddy(self.mui_categoria)

        self.retranslateUi(ModificarFacturacionBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.mui_cancelar, QtCore.SIGNAL("released()"), ModificarFacturacionBase.reject)
        QtCore.QObject.connect(self.mui_soporteTPV, QtCore.SIGNAL("toggled(bool)"), self.mui_plugins1.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ModificarFacturacionBase)

    def retranslateUi(self, ModificarFacturacionBase):
        ModificarFacturacionBase.setWindowTitle(QtGui.QApplication.translate("ModificarFacturacionBase", "Nueva Facturacion", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Nombre Empresa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Nombre Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Version de la Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_soporteTPV.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Activar Soporte para TPV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Plugins Instalados", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_vertodos.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Mostrar todos los plugins o solo los instalados", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_categoria.setItemText(0, QtGui.QApplication.translate("ModificarFacturacionBase", "Todas las Categorias", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_categoria.setItemText(1, QtGui.QApplication.translate("ModificarFacturacionBase", "Facturacion Generica", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_categoria.setItemText(2, QtGui.QApplication.translate("ModificarFacturacionBase", "Asociaciones de Padres de Alumnos", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_categoria.setItemText(3, QtGui.QApplication.translate("ModificarFacturacionBase", "Fabricacion y Trazabilidad", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_categoria.setItemText(4, QtGui.QApplication.translate("ModificarFacturacionBase", "IVA. Incluido", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_categoria.setItemText(5, QtGui.QApplication.translate("ModificarFacturacionBase", "Utilidades Genericas", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Descripcion", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Version Instalada", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("ModificarFacturacionBase", "Plugins BulmaFact", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins1.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins1.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Descripcion", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_plugins1.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Version Instalada", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("ModificarFacturacionBase", "Plugins BulmaTPV", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("ModificarFacturacionBase", "Consola", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_actualizardatabase.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Actualizar Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_aceptar.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Aplicar plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_hacerbackup.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Hacer copia de Seguridad", None, QtGui.QApplication.UnicodeUTF8))
        self.mui_cancelar.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Cerrar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ModificarFacturacionBase", "Categoria", None, QtGui.QApplication.UnicodeUTF8))

