#!/usr/bin/python
# -*- coding: utf-8 -*-

__version__ = "$Revision: 0.1 $"[11:-2]
__date__ = "$Date: 2008/03/21 08:09:13 $"[7:-2]
__author__ = "Tomeu Borras <tborras@conetxia.com>"
__all__ = ["bulmasetup"]
__doc__ = "Sistema de instalacion y mantenimiento de Bases de Datos para BulmaGes.\r\n"

import commands
import sys
import os

def main(args):
  if os.environ.get('KDE_FULL_SESSION') == 'true':
    os.execv("/usr/bin/kdesudo",["kdesudo", "bulmasetup"])
  else:
    os.execv("/usr/bin/gksudo",["gksudo", "bulmasetup"])

if __name__=="__main__":
    main(sys.argv)
