# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 


  TEMPLATE = subdirs
  SUBDIRS += fuentes/src/estadisticas 
  SUBDIRS += bulmalib
  SUBDIRS += fuentes
  SUBDIRS += bulmafact
  SUBDIRS += bulmatpv
  SUBDIRS += introbulmages
  