# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

CONFIG = ordered

  TEMPLATE = subdirs

  SUBDIRS += bulmalib
  SUBDIRS += bulmafact
  SUBDIRS += bulmacont
#  SUBDIRS += bulmatpv
  SUBDIRS += bulmages
  