# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: .
# Target is a subdirs project

TEMPLATE = subdirs
SUBDIRS += src/contabilidad
SUBDIRS += src/plugin
SUBDIRS += src/plugincorrector
SUBDIRS += src/pluginadocumental
# SUBDIRS += src/pluginestadisticas
SUBDIRS += src/pluginonline
SUBDIRS += src/pluginpychart
SUBDIRS += src/pluginregistroiva

