# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: .
# Target is a subdirs project

TEMPLATE = subdirs
SUBDIRS += src/contabilidad

#Pendientes de migrar a Qt4 es preferible que no compilen
#SUBDIRS += src/plugin
#SUBDIRS += src/plugincorrector
#SUBDIRS += src/pluginadocumental
# SUBDIRS += src/pluginestadisticas
#SUBDIRS += src/pluginonline
#SUBDIRS += src/pluginpychart
#SUBDIRS += src/pluginregistroiva

