#ifndef PDEFS_PLUGINBF_RESUMENARTICULO_H
#define PDEFS_PLUGINBF_RESUMENARTICULO_H


#ifdef Q_OS_WIN32

#ifdef PLUGINBF_RESUMENARTICULO
#define PLUGINBF_RESUMENARTICULO_EXPORT __declspec(dllexport)
#else
#define PLUGINBF_RESUMENARTICULO_EXPORT __declspec(dllimport)
#endif

#else

#define PLUGINBF_RESUMENARTICULO_EXPORT

#endif


#endif

