#ifndef PDEFS_PLUGINBT_ALIASTALLASYCOLORES2_H
#define PDEFS_PLUGINBT_ALIASTALLASYCOLORES2_H


#ifdef Q_OS_WIN32

#ifdef PLUGINBT_ALIASTALLASYCOLORES2
#define PLUGINBT_ALIASTALLASYCOLORES2_EXPORT __declspec(dllexport)
#else
#define PLUGINBT_ALIASTALLASYCOLORES2_EXPORT __declspec(dllimport)
#endif

#else

#define PLUGINBT_ALIASTALLASYCOLORES2_EXPORT

#endif


#endif

