<script language="php">
$title = "Hacerse socio";
// =================================================
$body = '
<h1>Pasos a seguir</h1>
<p>Todo aquel que esté interesado en asociarse deberá enviar a la secretaria lo siguiente (entregado en mano, por mail - cmarco at conetxia.com -, por correo normal... como prefiráis)</p>
<p>
-Datos personales: <br>
<ul>
<li>Nombre y Apellidos</li>
<li>Nacionalidad</li>
<li>Dirección Física (calle, número, piso, código postal)</li>
<li>Correo Electrónico (No tiene por qué ser el mismo que el de la lista)</li>
<li>Fecha de Nacimiento</li>
</ul>
- Copia (puede ser escaneada) del DNI, NIF, pasaporte, permiso de residencia o cualquier otro documento acreditativo de la identidad según el caso. (sólo uno de los documentos... ¿eh?) <br>
- Documento que certifique la voluntad de ser socio de la asociación (en principio, con que pongáis "quiero ser socio en el e-mail, bastará)"</p>
<br>

'; 
// =================================================
</script>