<script language="php">
$title = "Contactar con Iglues";
// =================================================
$body = '

<p>Hemos pensado que aquí deberían estar los correos de los miembros de la 
junta directiva, y que estas cuentas quizás deberían ser genéricas de la 
asociación (p.e presidencia@iglues.org). También la dirección de 
contacto podríamos la que consta en los estatutos y como teléfono el de 
la misma dirección pues creemos que da una mayor confianza a personas y 
empresas  una ubicación física que la propiamente "virtual".</p>

'; 
// =================================================
</script>