<script language="php">
$title = "Preguntas frequentes (FAQ)";
// =================================================
$body = '

<p>Aparte de lo evidente, hemos comentado de poner los temas que se van 
tratando en la lista y que susciten un cierto interés, a modo de resumen 
al estilo de las Debian Weekly News 
<http://www.nl.debian.org/News/weekly/2004/28/>.
</p>

'; 
// =================================================
</script>