<script language="php">
$title = "Preguntas frecuentes (FAQ)";
// =================================================
$body = '

<H1>FAQ</H1>

<b>Pregunta: Que numero saldra en la loteria la semana que viene.</b>
<p>
Respuesta: No lo sabemos, pero si quieres podemos crear un sistema de números aleatorios que te dará una respuesta (igual de invalida que cualquier otra que nosotros podamos darte).
</P>

<B>Pregunta: Quiero migrar mi empresa a Linux, podeis ayudarme.</B>
<P>Respuesta: La asociación tiene como fin permitir la migración de empresas al mundo del "open source". No es una empresa que ofrezca servicios informáticos.<BR>
Tenemos disponible en la seccion de "Contactos" a todos aquellos profesionales que ofrecen sus servicios sobre programas empresariales "open source". Dirijase a esa sección para encontrar un profesional cerca de donde está usted y pongase en contacto con él que estará encantado de ayudarle.</p><BR>

<B>Pregunta: Tengo problemas con alguno de sus programas. ¿Que debo hacer?</B>
<P>Respuesta: Debemos distinguir dos tipos de problemas. Por una parte aquellos problemas o mejoras que afectan a cualquier usuario de nuestros programas, como puede ser un bug, o una modificación debida a factores globales (p.e. una nueva legislación). 
<br>
Por otra parte, otro tipo de problemas son aquellos que afectan a uno en particular y que no son debidos a un error en los programas. Para solucionar estos últimos debe recurrir a un informático cualificado.
<br>Por norma general, en estos casos lo más habitual es preguntar en la lista de distribución y allí se le orientará de la forma adecuada.
</P>


<B>Pregunta: ¿Por qué debo asociarme? Ventajas de ser socio</B>
<P>Respuesta: En primer lugar porque formas parte de una iniciativa ventajosa para la sociedad en general.<br>
En segundo lugar, descuentos en el merchandising que la asociación distribuya<br>
En tercer lugar, la posibilidad de estar en contacto con los otros socios y desarrolladores de los proyectos en los que participes.<br>
En cuarto lugar, la posibilidad de proponer nuevos proyectos, y formar grupos de trabajo para desarrollarlos.<br>
Otra ventaja es el hecho de poder influir en las decisiones de la asociación mediante el sistema de voto, además de poder formar parte (previas elecciones) de la Junta Directiva <br>
Otra ventaja es poder ser subvencionado por la asociación en el desarrollo de nuevos módulos o proyectos.<br>
Finalmente, publicidad proporcionada por la asociación al figurar en la lista de contactos de ésta como distribuidor o desarrollador.
</P>


<B>Pregunta: Me gusta vuestra idea. Quiero colaborar ¿Que hago?</B>
<P>Respuesta: En primer lugar inscribirte como socio por las ventajas que ello te ofrece. En segundo lugar inscribirte en la lista de correo de la asociación para entrar en contacto con la gente de la asociación. Y finalmente ubicarte en aquello que te guste, desees o veas que sabes hacer mejor dentro de las necesidades de los proyectos existentes.<br>
Aunque los proyectos tienen directores y hay listas de tareas por desarrollar, no existe una estructura jerárquica, con lo cual uno no debe esperar a que se le pida que haga algo sino que cualquiera puede escoger un punto pendiente y desarrollarlo. Las tareas de coordinación se realizan básicamente en la lista, siendo ésta la base de la comunicación entre los grupos de desarrollo.
<BR> No esperes que nadie te coordine. Coordinate tu mismo con quien debas hacerlo en función de la labor que quieras llevar a cabo.
</P>


'; 
// =================================================
</script>