<script language="php">
$title = "La Asociaci&oacute;n";
// =================================================
$body = '
<h1>La Asociación</h1>
<p>En el año 2001 nació un proyecto, BulmaGés, fruto de la creencia de que es necesario dotar al mundo del software libre, y en concreto a GNU/Linux, de herramientas de gestión empresarial libres y desmostrar así que es opción seria y a tener en cuenta.</p>
<p>En octubre del año 2002 se empezó a desarrollar el programa de contabilidad. A partir de entonces se han ido sumando colaboradores de diferentes lugares, unos en la isla y otros en la península. Actualmente hay un equipo de gente especializada en diversas áreas, todo se relaciona al final con un objetivo común.</p>
<p>La gran difusión del proyecto que culmina en la obtención del premio Solico 2003 por ser el proyecto de mayor calidad. Esto junto al hecho de que la aplicación está funcionando en diversas entidades nos lleva a la necesidad de dotar de un ámbito legal al trabajo que estamos realizando.
Es en este momento cuando nace IGLUES como organización responsable de los proyectos realizados, en curso y de los futuros desarrollos del grupo de gente que la formamos.</p>
<p>Desde este el ámbito legal de organización sin ánimo de lucro se pretende realizar las tareas de representación y difusión de los proyectos allá donde fuera necesario, ser la responsable de los recursos propios de la asociación así como de su gestión, asegurando que se utilizan para los fines que compartimos todos sus miembros.
</p>

'; 
// =================================================
</script>