<script language="php">
$title = "Bienvenido a nuestra web";
// =================================================
$body = '
<div id="noticies">
<!-- <img src=""> -->
<h1>&Uacute;ltimas Noticias</h1>
<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>31/01/2005</td>
<td><center><b>1ª Convención Igluera (2005)</b></center></td>
</tr>
<tr>
<td colspan=2>Se celebra la primera convención internacional de Iglues que tendrá lugar en Palma de Mallorca los dias 5 y 6 de Marzo:<br>
Ya han confirmado su asistencia los Iglues de Castellón y Londres  con 3 y 1 representantes.<BR>
La convención es una toma de contacto entre los distintos miembros de la Asociación y en el planing se incluye paseo marchoso por la ciudad
y degustación de platos típicos.<BR>
<BR>
Para asisistir a la convención es preciso confirmar previamente la asistencia a través de la lista.

</td>
</tr>
</table>

<br>


<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>17/01/2005</td>
<td><center><b>IGLUES en eventos informáticos 2005</b></center></td>
</tr>
<tr>
<td colspan=2>Estamos muy contentos de poder comunicar que vamos a participar como ponentes en diversos eventos informáticos, jornadas de sofware libre y lan-parties. El calendario actualmente es el siguiente:<br>
        <ul>
                <li>Del 17 al 20 de Febrero: <A href="http://www.clubibosim.org" TARGET="nueva">Feria de Informática y Nuevas Tecnologías</A></li>
                <li>Dias 5, 11 al 12 de Marzo:  <A href="http://linuxcordoba.org" TARGET="nueva">Jornadas Temáticas de Software Libre de Córdoba</A></li>
                <li>Del 14 al 16 de Marzo: <A href="http://asturlinux.org/jornadas2005/index.php" TARGET="nueva">V Jornadas de Software Libre en Asturias</A></li>
                <li>Del 18 al 20 de Marzo: <A href="http://reuslanparty.org/index_es.htm" TARGET="nueva">Reus-Lan-Party</A></li>
        </ul>
        Gracias a todos por contar con nosotros :-) .

</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>21/12/2004</td>
<td><center><b>Directiva de Patentes de Programas en la lista de Puntos A del Consejo Agrícola</b></center></td>
</tr>
<tr>
<td colspan=2>Nos sentimos muy preocupados por lo que representa que la conocida como <i>"directiva de patentes de software"</i> de comisión se pueda aprovar hoy martes 21 sobre el sector informático. El mayor peligro actual para la innovacion, hasta asociaciones de informáticos se han manifestado en contra.
<br>
Más información en:
<ul>
<li><a href="http://proinnova.hispalinux.es/">Proinnova</a> [ES]
</li>
<li><a href="http://bulma.net/body.phtml?nIdNoticia=2132">Bulma.net</a> [ES]</li>
<li><a href="http://demo.ffii.org/">Acciones en la Red</a>
</li><li><a href="http://swpat.ffii.org/letter/cons0406/index.es.html">Petici&oacute;n Urgente</a> [ES]

</li><li><a href="http://kwiki.ffii.org/ConsRevers04En">Revirtamos la Decisi&oacute;n del Consejo del 18 de mayo</a>
</li>
<li><a href="http://kwiki.ffii.org/SwpatcninoEs">Noticias FFII sobre Patentes de Programaci&oacute;n</a> [ES]</li>
<li><a href="http://swpat.ffii.org/">FFII: Patentes de Programas en Europa</a>
<li><a href="http://www.nosoftwarepatents.com/es/m/intro/index.html">NoSoftwarePatents.com</a> [ES]</li>
<li><a href="http://barrapunto.com/article.pl?sid=04/12/19/0825236">Barrapunto.com</a> [ES]</li>
</ul>
<br><span style="color: rgb(255, 0, 0);">Actualizaci&oacute;n 22/12/2004:</span> La propuesta fué detenida gracias a que el representate de Polonia pidió que se borrara ese punto del acta. Se le puede dar las gracias <a href="http://thankpoland.info/" TARGET="nueva">firmando en esta carta</a>
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>5/12/2004</td>
<td><center><b>Disponible Manual de Doxigen</b></center></td>
</tr>
<tr>
<td colspan=2>El pasado día 1 de diciembre, David Gutierrez subió al CVS la primera versión del manual de Doxigen, de lectura muy recomendable especialmente para los desarrolladores. Se puede leer en la sección de <A href="http://www.iglues.org/home.php?go=manuales#doxmanual">documentación</A> de nuestra web.
</td>
</tr>
</table>

<br>


<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>28/11/2004</td>
<td><center><b>Junta Directiva de IGLUES</b></center></td>
</tr>
<tr>
<td colspan=2>El pasado domingo 28 de noviembre tuvo lugar la primera reunión de la nueva Junta Directiva. Cabe destacar la gran participación por parte de los soci@s tanto en asistencia como en el debate de los temas que se discutieron. En líneas generales se trataron los temas siguientes:
<ul>
<li>Creación de un inventario de proyectos en de la asociación con las personas que los integran.</li>
<li>Documentación orientada a presentar el software libre en general y el nuestro en particular a las empresas, en forma tanto de arículos como de presentacones.</li>
<li>Presentación de la asociación y de BulmaGés al Ayuntamiento de Benicarló y a AJOVE (Asociación de Jóvenes Empresarios de Castellón).</li>
<li>Realización de manuales de las aplicaciones.</li>
<li>Documentación técnica con DOXIGEN.</li>
</ul>
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>22/11/2004</td>
<td><center><b>Primer Screenshot de Bulmafact</b></center></td>
</tr>
<tr>
<td colspan=2>Hoy Tomeu Borràs ha mostrado la primera imagen de la futura facturación donde se pueden ver algunos de los puntos que ya se han realizado. Puede verse <A href="http://www.iglues.org/bulmafact1.png" TARGET="nueva">aquí</A>.
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>20/11/2004</td>
<td><center><b>Aplazada Junta Directiva</b></center></td>
</tr>
<tr>
<td colspan=2>Dado que en la fecha fijada para la Junta Directiva a varios de los miembros les es imposible asistir ésta se aplaza hasta el próximo domingo dia 28 de noviembre con el mismo horario y programa.
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>17/11/2004</td>
<td><center><b>Finalizado Concurso de Iconos</b></center></td>
</tr>
<tr>
<td colspan=2>Damos por concluido el concurso de icono y que tras la votación el ganador ha sido Raül. (Aunque con un margen muy muy estrecho !!!)<br>
Enhorabuena!!!!!!!!!!
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>11/11/2004</td>
<td><center><b>Reunión Junta Directiva domingo 21 de noviembre</b></center></td>
</tr>
<tr>
<td colspan=2>Se convoca reunión de la Junta Directiva para el próximo domingo 21 de noviembre a las 17:00 horas en primera convocatoria y a las 17:30 en segunda convocatoria. La reunión tratará de formalizar las responsabilidades y trazar objetivos. Podeis ver el correo de la convocatoria en la <A href="http://llistes.bulma.net/pipermail/bulmages/2004-November/001401.html">lista</A>. Sólo recordar que que por decisión en Asamblea General todos los socios son vocales de la Junta.
</td>
</tr>
</table>



</div>
';
// =================================================
</script>