<script language="php">
$title = "Bienvenido a nuestra web";
// =================================================
$body = '
<div id="noticies">
<!-- <img src=""> -->
<h1>&Uacute;ltimas Noticias</h1>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>23/02/2005</td>
<td><center><b>Liberada Primera Versions de RTK::Report Toolkit</b></center></td>
</tr>
<tr>
<td colspan=2>Santiago Capel ha anunciado en la lista de correo de bulmagés la liberación de la primera versión de Reports. RTK es una grupo de herramientas bajo licencia GNU GPL para generar informes desde diferentes fuentes (que incluyen ficheros de texto plano, XML y SQL) a distintos formatos (ficheros de texto plano, HTML, OppenOffice Calc y en un visualizador gráfico propio) mediante un sistema de plantillas. 
<br><br>
Es el primer intento de crear una herramienta de generación de informes de calidad, al estilo de Crystal Reports(C), o Ms Access(C). El código está totalmente orientado a objetos y diseñado para ser extremadamente escalable, pequeño y eficiente.<br><br>
La página del proyecto es: <A href="http://reports.sourceforge.net" target="nueva">http://reports.sourceforge.net</A>  
<br><br>Cualquier comentario sobre esta herramienta podeis enviarla a Santiago Capel Torres (santiagocapel[a t]yahoo[do t]es).
<br><br><B><I>¡¡¡Enhorabuena Santi!!!</I></B>
</td>
</tr>
</table>

<br>


<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>12/02/2005</td>
<td><center><b>Presentación de BulmaGés en INTEC</b></center></td>
</tr>
<tr>
<td colspan=2>El pasado dia 12 de febrero Tomeu Borràs presentó BulmaGés en la Feria de Informática y Nuevas Tecnologías en Ibiza, invitado por el <A href="http://www.clubibosim.org" target="nueva">Club Ibosim</A>. La presentación fué un éxito teniendo en cuenta la afluencia de público al evento en general. La ponencia trató sobre nuestra asociación, el software libre y las empresas, el Proyecto BulmaGés, herramientas de desarrollo y finalizó con una pequeña demostración de los módulos BulmaCont y BulmaFact.<br>
Queremos agradecer a los miembros del <A href="http://www.clubibosim.org" target="nueva">Club Ibosim</A> su hospitalidad y las atenciones que tuvieron con nosotros. Quedamos gratamente sorprendidos de conocer más esta asociación de amigos de la informática que lleva realizado un largo camino desde sus inicios con la red Fidonet hasta la actualidad.
<br>
<A href="http://www.iglues.org/ibosim/" target="nueva">Aquí</A> podeis ver unas fotos del evento y posterior cena.
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>17/02/2005</td>
<td><center><b>Actualizada Documentación de RTK Reports</b></center></td>
</tr>
<tr>
<td colspan=2>El pasado dia 3 de febrero Santiago Capel actualizó la documentación de de RTK creando un pequeño tutorial que muestra 
como crear un informe a partir del fichero /etc/passwd. Está en inglés... en <A href="http://reports.sourceforge.net" target="nueva">http://reports.sourceforge.net</A><br>
<br>
También ha arreglado algunos pequeños fallos y ahora parece que está funcionando perfectamente. Con esto, se da casi por concluida la primera versión de RTK Reports.
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>16/02/2005</td>
<td><center><b>Liberada Nueva Versión BulmaGés 0.4.5</b></center></td>
</tr>
<tr>
<td colspan=2>Hoy Tomeu Borràs ha anunciado en la lista de BulmaGés la liberación de la nueva versión empaquetada 0.4.5. En ella se incluyen cambios como la entrada de líneas de IVA, gestión de cobros y pagos, además de depuración de los bugs encontrados hasta el momento de la liberación. También se han eliminado aquellas opciones que no eran operativas y que inducian a confusión, que se habían incluido en la versión anterior.<br> 
Aquel que desee ver y probar los últimos cambios del proyecto debe recurrir al CVS y compilar la versión de desarrollo, que incluye otros módulos que están en fase de desarrollo. 
<br><br>La nueva versión se puede bajar de <A href="http://prdownloads.sourceforge.net/bulmages/installbulmages_0_4_5.tgz?download" TARGET="nueva">aquí</A>. La versión de desarrollo está accesible como siempre desde el cvs de sourceforge.net.
</td>
</tr>
</table>

<br>


<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>31/01/2005</td>
<td><center><b>1ª Convención Igluera (2005)</b></center></td>
</tr>
<tr>
<td colspan=2>Se celebra la primera convención internacional de Iglues que tendrá lugar en Palma de Mallorca los dias 5 y 6 de Marzo:<br>
Ya han confirmado su asistencia los Iglues de Castellón y Londres  con 3 y 1 representantes.<BR>
La convención es una toma de contacto entre los distintos miembros de la Asociación y en el planing se incluye paseo marchoso por la ciudad
y degustación de platos típicos.<BR>
<BR>
Para asisistir a la convención es preciso confirmar previamente la asistencia a través de la lista.

</td>
</tr>
</table>

<br>


<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>17/01/2005</td>
<td><center><b>IGLUES en eventos informáticos 2005</b></center></td>
</tr>
<tr>
<td colspan=2>Estamos muy contentos de poder comunicar que vamos a participar como ponentes en diversos eventos informáticos, jornadas de sofware libre y lan-parties. El calendario actualmente es el siguiente:<br>
        <ul>
                <li>Del 17 al 20 de Febrero: <A href="http://www.clubibosim.org" TARGET="nueva">Feria de Informática y Nuevas Tecnologías</A></li>
                <li>Dias 5, 11 al 12 de Marzo:  <A href="http://linuxcordoba.org" TARGET="nueva">Jornadas Temáticas de Software Libre de Córdoba</A></li>
                <li>Del 14 al 16 de Marzo: <A href="http://asturlinux.org/jornadas2005/index.php" TARGET="nueva">V Jornadas de Software Libre en Asturias</A></li>
                <li>Del 18 al 20 de Marzo: <A href="http://reuslanparty.org/index_es.htm" TARGET="nueva">Reus-Lan-Party</A></li>
        </ul>
        Gracias a todos por contar con nosotros :-) .

</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>21/12/2004</td>
<td><center><b>Directiva de Patentes de Programas en la lista de Puntos A del Consejo Agrícola</b></center></td>
</tr>
<tr>
<td colspan=2>Nos sentimos muy preocupados por lo que representa que la conocida como <i>"directiva de patentes de software"</i> de comisión se pueda aprovar hoy martes 21 sobre el sector informático. El mayor peligro actual para la innovacion, hasta asociaciones de informáticos se han manifestado en contra.
<br>
Más información en:
<ul>
<li><a href="http://proinnova.hispalinux.es/">Proinnova</a> [ES]
</li>
<li><a href="http://bulma.net/body.phtml?nIdNoticia=2132">Bulma.net</a> [ES]</li>
<li><a href="http://demo.ffii.org/">Acciones en la Red</a>
</li><li><a href="http://swpat.ffii.org/letter/cons0406/index.es.html">Petici&oacute;n Urgente</a> [ES]

</li><li><a href="http://kwiki.ffii.org/ConsRevers04En">Revirtamos la Decisi&oacute;n del Consejo del 18 de mayo</a>
</li>
<li><a href="http://kwiki.ffii.org/SwpatcninoEs">Noticias FFII sobre Patentes de Programaci&oacute;n</a> [ES]</li>
<li><a href="http://swpat.ffii.org/">FFII: Patentes de Programas en Europa</a>
<li><a href="http://www.nosoftwarepatents.com/es/m/intro/index.html">NoSoftwarePatents.com</a> [ES]</li>
<li><a href="http://barrapunto.com/article.pl?sid=04/12/19/0825236">Barrapunto.com</a> [ES]</li>
</ul>
<br><span style="color: rgb(255, 0, 0);">Actualizaci&oacute;n 22/12/2004:</span> La propuesta fué detenida gracias a que el representate de Polonia pidió que se borrara ese punto del acta. Se le puede dar las gracias <a href="http://thankpoland.info/" TARGET="nueva">firmando en esta carta</a>
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>5/12/2004</td>
<td><center><b>Disponible Manual de Doxigen</b></center></td>
</tr>
<tr>
<td colspan=2>El pasado día 1 de diciembre, David Gutierrez subió al CVS la primera versión del manual de Doxigen, de lectura muy recomendable especialmente para los desarrolladores. Se puede leer en la sección de <A href="http://www.iglues.org/home.php?go=manuales#doxmanual">documentación</A> de nuestra web.
</td>
</tr>
</table>


</div>
';
// =================================================
</script>