<script language="php">
$title = "Bienvenido a nuestra web";
// =================================================
$body = '
<div id="noticies">
<!-- <img src=""> -->
<h1>&Uacute;ltimas Noticias</h1>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>06/10/2004</td>
<td><center><b>Disponibles Manuales Básicos de Jabber y CVS</b></center></td>
</tr>
<tr>
<td colspan=2>Ante el interés que ha suscitado el proyecto despues de la publicación de la noticia de la creación de IGLUES en <A href="http://barrapunto.com">Barrapunto</A>, <A href="http://bulma.net">Bulma</A> y en la publicación Todo Linux, se ha creido conveniente documentar dos de los programas que nos son de utilidad en nuestro proyecto, tanto por el aspecto del desarrollo (manual de CVS) como a nivel de relación social (manual de Jabber). Ambos se encuentran en la sección de <A href="http://www.iglues.org/home.php?go=manuales">documentación</A> de nuestra web.
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>11/10/2004</td>
<td><center><b>Concurso para crear la iconografía de BulmaFact</b></center></td>
</tr>
<tr>
<td colspan=2>Ante la necesidad de realizar la iconografía para BulmaFact, se convoca un concurso consistente en 
la realización de los iconos para el programa de facturación. El <A href="./img/pegatinaypin.jpg" TARGET="nueva">premio</A>, el hecho de que los iconos se utilizarán en el programa,
una pegatina y un pin de la Free Software Foundation.<br>
Los iconos a realizar son: proveedores, clientes, compras ventas, artículos, caja, bancos, facturas y partes de trabajo.</p>
<br>
Las normas del concurso son:
<ol>
        <li>No vale usar el lenguaje escrito.</li>
        <li>Los iconos deben tener 32x32 píxeles y 256 colores.</li>
        <li>Si son libres se pueden copiar o coger de otra parte.</li>
        <li>Cada participante puede presentar tantos iconos como crea oportuno.</li>
        <li>El jurado, como viene siendo habitual, será la votación popular.</li>
	<li>El plazo de presentación es el dia 11/11/2004</li>
</ol>
<p>
Se puede leer el anuncio oficial en <A HREF="http://llistes.bulma.net/pipermail/bulmages/2004-October/001201.html" TARGET="nueva">nuestra lista de correo<A>
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>06/10/2004</td>
<td><center><b>Publicada última versión de BulmaGés (0.41)</b></center></td>
</tr>
<tr>
<td colspan=2>Hoy Tomeu Borrás ha anunciado la publicación de la última versión de BulmaGés (0.41) que incluye entre otras mejoras, cambio del splash de presentación y un nuevo script de instalación.
Para más información visitar <A HREF="http://bulmages.bulma.net" TARGET="nueva">bulmages.bulma.net<A>
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>03/10/2004</td>
<td><center><b>Primera Asamblea General</b></center></td>
</tr>
<tr>
<td colspan=2> Entre otros puntos se escogió a la nueva junta directiva que queda tal que así:
Presidente: Josep Burción, Vicepresidente: René Mérou, Secretaria: Cristina Marco. Tesorero: Tomeu Borràs<br>
Vocales: Joan Miquel Torres, Santiago Capel, Laura Edo, Pablo Braulio, Josep María Estopà<br>
El resto de socios también deberían ser vocales, según acuerdo en la asamblea. Para ello bastará la petición de serlo a la Junta Directiva.<br>
El resto de acuerdos se pueden consultar en el <a href="http://www.iglues.org/actaxxx.pdf">acta</a> de la asamblea.
</td>
</tr>
</table>

<br>

<a href="http://www.iglues.org/home.php?go=noticias">Más noticias ...</a>
</div>
'; 
// =================================================
</script>