<script language="php">
$title = "Junta Directiva";
// =================================================
$body = '

<H1>Junta Directiva</H1>

<OL>
<LI> Pesidente: <A href="mailto:presidente@iglues.org">Josep Burción</A></LI>
	
<LI> Vicepresidente: <A href="mailto:vicepresidente@iglues.org">René Mérou</A></LI>

<LI> Secretario: <A href="mailto:secretario@iglues.org">Cristina Marco Hernández</A></LI>

<LI> Tesorero: <A href="mailto:tesorero@iglues.org">Tomeu Borrás Riera</A></LI>

</OL>

<br>

'; 
// =================================================
</script>