<script language="php">
$title = "Enlaces";
// =================================================
$body = '
<h1>Enlaces</h1>
<p>Aquí pensamos que podemos dividirlos en varios subapartados, como 
distribuciones de linux (y otros SO Libres?), herramientas de desarrollo 
y publicación (IDEs, servidores de aplicaciones, lenguajes...), otros 
proyectos en la misma línea que el nuestro, organizacione afines, ...</p>

<TABLE BORDER=1>
<TR>
<TD>
<A HREF="http://www.facturalux.org" TARGET="nueva">Facturalux</A><BR>
<P>Facturalux es un proyecto de la empresa InfoSial que pretende, al mismo tiempo que tener empresas en funcionamiento dotar de software libre al sistema operativo GNU/Linux.</P>

<A HREF="http://www.fisterra.org" TARGET="nueva">Fisterra</A><BR>
<P>Fisterra es un proyecto que ha realizado una facturación</P>

<A HREF="http://galopin.sinuh.org" TARGET="nueva">Galopín</A><BR>
<P>Es un sencillo programa de facturación y control de existencias, liberado bajo licencia GPL, realizado en lenguaje PHP y utilizando como motor de bases de datos MySQL. Pensado para una pequeña empresa permite su utilización en una red local.</P>




</TD><TD>

</TD>
</TR>
</TABLE>

'; 
// =================================================
</script>