<script language="php">
$title = "Enlaces";
// =================================================
$body = '
<h1>Enlaces</h1>
<table border=0 cellspacing="0" class="link">
<tr class="head">
<td><center><b>Proyectos afines</b></center></td>
</tr>
<tr>
<td>
<A HREF="http://www.facturalux.org" TARGET="nueva">Facturalux</A><BR>
<P>Facturalux es un proyecto de la empresa InfoSial que pretende, al mismo tiempo que tener empresas en funcionamiento dotar de software libre al sistema operativo GNU/Linux.</P>
<br>
</td>
</tr>
<tr>
<td>
<A HREF="http://www.fisterra.org" TARGET="nueva">Fisterra</A><BR>
<P>Fisterra es un proyecto que ha realizado una facturación</P><br>
</td>
</tr>
<tr>
<td>
<A HREF="http://galopin.sinuh.org" TARGET="nueva">Galopín</A><BR>
<P>Es un sencillo programa de facturación y control de existencias, liberado bajo licencia GPL, realizado en lenguaje PHP y utilizando como motor de bases de datos MySQL. Pensado para una pequeña empresa permite su utilización en una red local.</P><br>
</td>
</tr>
<tr>
<td>
<A HREF="http://www.josepmguasch.net/guco/guco.html" TARGET="nueva">Guco</A><BR>
<P>Programa de contabilidad GPL en catalán.</P><br>
</td>
</tr>
<tr>
<td>
<A HREF="http://www.aspl.es/fact/" TARGET="nueva">ASPL-Fact</A><BR>
<P>ASPL Fact es un nuevo sistema de facturación para GNU/Linux (aunque, en principio, podría compilar y funcionar en cualquier plataforma para la que glib esté disponible). Está basado en la Arquitectura AF, y se desarrolla bajo licencia GNU/GPL.</P><br>
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="link">
<tr class="head">
<td><center><b>Asociaciones Colaboradoras y Amigas</b></center></td>
</tr>
<tr>
<td>
<A HREF="http://bulma.net" TARGET="nueva">Bulma</A><BR>
<P>BULMA (Bisoños Usuarios de Linux de Mallorca y Alrededores) es una asociación sin ánimo de lucro,constituída de acuerdo a la ley, cuyo ámbito es el de la Comunidad Autónoma de Baleares, con unos objetivos entre los cuales se hallan: La divulgación y promoción del Software Libre, el apoyo a grupos de usuarios y desarrolladores de Software Libre en Baleares, promover el intercambio de experiencias relacionadas con el sistema operativo Linux y el Software Libre en general entre usuarios y desarrolladores, facilitar el acceso a Linux y al software libre a los residentes en Baleares, y de manera muy especial a alumnos y profesores de los distintos niveles del sistema de enseñanza, organización de cursos, congresos, conferencias y encuentros encaminados a conseguir todo lo anterior. </P>
<br>
</td>
</tr>
<tr>
<td>
<A HREF="http://www.clubibosim.org" TARGET="nueva">Club de Informática de Eivissa y Formentera</A><BR>
<P>un grupo de amigos que comparten una afición común: la informática y las comunicaciones a través del ordenador. Pese a su corta historia como Asociación -se fundó a finales de 1999-, el núcleo del club se gestó en las antiguas BBS y en una red de comunicaciones amateur: FIDONET, allá por el año 1991. Desde entonces venimos compartiendo experiencias, alegrias, problemillas, pero todo con una gran camaradería y procurando sobre todo divertirnos. </P>
<br>
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="link">
<tr class="head">
<td><center><b>Páginas de miembros</b></center></td>
</tr>
<tr>
<td>
<A HREF="http://www.burcion.com/" TARGET="nueva">Josep Burcion</A><BR>
<P>Página personal sobre BulmaGés, WiFi y IPv6</P>
<br>
</td>
</tr>
<tr>
<td>
<A HREF="http://www.mallorcaweb.net/joanmiquel/" TARGET="nueva">Joan Miquel Torres</A><BR>
<P>Página personal con datos personales, perfil profesional y proyectos.</P>
<br>
</td>
</tr>
<tr>
<td>
<A HREF="http://www.conetxia.com" TARGET="nueva">Tomeu Borràs</A><BR>
<P>Página oficial de Conetxia, empresa que proporciona soluciones eficaces y creativas en materia de consultoría informática, implantación y desarrollo de software y mejora de la estructura de gestión de sistemas informáticos dentro del ámbito de la empresa.</P>
<br>
</td>
</tr>
<tr>
<td>
<A HREF="http://www4.uji.es/~al021044/trabajo.htm" TARGET="nueva">Laura Edo</A><BR>
<P>Página que es un estudio sobre el software libre en la administración pública.</P>
<br>
</td>
</tr>
<tr>
<td>
<A HREF="http://mallorcaweb.net/rene/" TARGET="nueva">René Mérou</A><BR>
<P>Web de H con artículos muy diversos: Software libre, Nubes - meteorología, privacidad en la informatica , estrategia, escepticismo - racionalismo... y su weblog personal.</P>
<br>
</td>
</tr>
<tr>
<td>
<A HREF="http://www.humano.ya.com/bruli" TARGET="nueva">Pablo Braulio</A><BR>
<P>Página personal.</P>
<br>
</td>
</tr>
<tr>
<td>
<A HREF="http://www.todo-redes.com" TARGET="nueva">Fco. Javier</A><BR>
<P>Página oficial de Todo-Redes.com. Empresa sobre informática, redes, telecomunicaciones y formación basada en la implantación de software libre</P>
<br>
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="link">
<tr class="head">
<td><center><b>Distribuciones Open Source orientadas a empresas</b></center></td>
</tr>
<tr>
<td>
<A HREF="http://debian-enterprise.org" TARGET="nueva">Debian Enterprise</A><BR>
<P>Es una distribución basada en <a href="http://www.debian.org" TARGET="nueva">Debian GNU/Linux</a> orientada a estándares mundiales de fiabilidad, disponibilidad, seguridad y rendimiento.</P>
<br>
</td>
</tr>
<tr>
<td>
<A HREF="http://userlinux.com" TARGET="nueva">UserLinux</A><BR>
<P>Proveer de un sistema operativo GNU/Linux para los negocios, libre, de calidad, acompañado de certificaciones, servicio y opciones de soporte orientadas a fomentar la productividad y seguridad y a su vez de reducir el coste total.</P>
<br>
</td>
</tr>
</table>
<br>

'; 
// =================================================
</script>