<script language="php">
$title = "Listas de correo";
// =================================================
$body = '

<H1> Listas de Correo </H1>

<P>En estos momentos la asociación dispone de una lista de correo donde se concentra todo el desarrollo de proyectos.</P>

<P>Nuestra lista es BulmaGés. Para escribir en la lista uno debe inscribirse previamente</P>

<A HREF="http://llistes.bulma.net/mailman/listinfo/bulmages" >http://llistes.bulma.net/mailman/listinfo/bulmages</A>

<BR>
'; 
// =================================================
</script>