<script language="php">
$title = "";
// =================================================
$body = '

<H1> Listas de Correo </H1>

<P>En estos momentos la asociación dispone de una lista de correo donde se concentra todo el desarrollo de proyectos.</P>

<P>Esa lista es la de BulmaGés. Para escribir en la lista uno debe inscribirse previamente</P>

<A HREF="http://llistes.bulma.net/mailman/listinfo/bulmages" >http://llistes.bulma.net/mailman/listinfo/bulmages</A>

'; 
// =================================================
</script>