<script language="php">
$title = "Documentación";
// =================================================
$body = '

<H1> Documentación </H1>

<table border=0 cellspacing="0" class="link">
<tr class="head">
<td><center><b>Manuales</b></center></td>
</tr>
<tr>
<td>
<A HREF="./manuales/jabber/index.html" TARGET="nueva">Jabber como medio de comunicación social Libre</A><BR>
<P>Manual introductorio al uso del sistema de mensajería instantánea Jabber, orientado a aquellas personas que nunca hayan usado este sistema de mensajería.</P>
<A HREF="./documentos/manualjabber.pdf" TARGET="nueva">Versión PDF</A>
<br>
</td>
</tr>
<tr><td><br></td></tr>
<tr>
<td>
<A HREF="./documentos/cvs.pdf" TARGET="nueva">CVS como herramienta de desarrollo compartido</A><BR>
<P>Manual básico de uso del sistema de control de versiones CVS a partir del cliente gráfico Cervisia. El manual usa como ejemplo la estructura del CVS de BulmaGés, para aquellos desarrolladores interesados en el proyecto.</P>

<br>
</td>
</tr>
<tr>
<td>
<BASE href="doxmanual"><A HREF="./manuales/doxmanual/html/" TARGET="nueva">Manual de Doxigen</A><BR>
<P>Contiene los comandos más básicos para empezar a manejarlo y habituarse a documentar 
el código.</P>

<br>
</td>
</tr>
</table>

'; 
// =================================================
</script>