<script language="php">
$title = "Documentación";
// =================================================
$body = '

<H1> Documentación </H1>

<table border=0 cellspacing="0" class="link">
<tr class="head">
<td><center><b>Manuales</b></center></td>
</tr>
<tr>
<td>
<A HREF="./documentos/manualjabber.pdf" TARGET="nueva">Manual de Jabber</A><BR>
<P>Manual introductorio al uso del sistema de mensajería instantánea Jabber, orientado a aquellas personas que nunca hayan usado este sistema de mensajería.</P>
<br>
</td>
</tr>
</table>

'; 
// =================================================
</script>