<?php

$menu = array (
	'Inicio'		=> 'inicio',
	'La Asociación' => 'iglues',
	'Estatutos'		=> 'estatutos',
	'Noticias'		=> 'noticias',
	'Documentación'		=> 'manuales',
	'Proyectos'		=> 'proyectos',
	'Preguntas frecuentes (FAQ)'	=> 'faq',
	'Hacerse socio'	=> 'asociarse',
	'Listas de correo'	=> 'maillists',
	'Enlaces'			=> 'links',
	'Contactar con Iglues'	=> 'contacto',
	'Junta Directiva'		=> 'jdirectiva'
);


// 	'Otros'			=> 'otros',

?>