<?php

$menu = array (
	'Inicio'		=> 'inicio',
	'La Asociación' => 'iglues',
	'Estatutos'		=> 'estatutos',
	'Noticias'		=> 'noticias',
	'Manuales'		=> 'manuales',
	'Otros'			=> 'otros',
	'Proyectos'		=> 'proyectos',
	'Preguntas frequentes (FAQ)'	=> 'faq',
	'Hacerse socio'	=> 'asociarse',
	'Lists de correo'	=> 'maillists',
	'Enlaces'			=> 'links',
	'Contactar con Iglues'	=> 'contacto',
	'Junta Directiva'		=> 'jdirectiva'
);

?>