<script language="php">
$title = "Noticias";
// =================================================
$body = '

<div id="noticies">
<img src="">
<h1>Noticias</h1>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>17/09/2004</td>
<td><center><b>Convocatoria primera Asamblea General</b></center></td>
</tr>
<tr>
<td colspan=2>Se convoca Asamblea General de IGLUES, para tratar además de otros puntos que se pueden ver en la <a href="http://www.iglues.org/asamblea.pdf">convocatoria</a>, la elección de la Junta Directiva anual.</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>25/07/2004</td>
<td><center><b>Primera Junta Directiva</b></center></td>
</tr>
<tr>
<td colspan=2>Primera Junta Directiva en la que se han tratado los temas siguientes: Logos, P&aacute;gina Web de la asociación ... </td>
</tr>
</table></table>

<br>


<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>07/07/2004</td>
<td><center><b>Nacicimiento de IGLUES</b></center></td>
</tr>
<tr>
<td colspan=2>Hoy comienza a andar la asociaci&oacute;n IGLUES, Iniciativa de Gestion Libre Universal para Empresas y Sociedades</td>
</tr>
</table>

<BR>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>05/07/2004</td>
<td><center><b>Propuesta de Junta Directiva provisional de IGLUES</b></center></td>
</tr>
<tr>
<td colspan=2>Se ha propuesto, en plan dictatorial, la junta directiva provisional de la asociación. Dicha junta tiene como misión velar por la asociación mientras esta no alcance un estado normal de funcionamiento.

Dicha Junta se compone por los siguientes cargos:<BR><BR>
<UL>
<LI>Presidente: Tomeu Borrás.<BR>
<LI>Vicepresidente 1º: Josep Burción.<BR>
<LI>Vicepresidente 2º: Joan Miquel Torres.<BR>
<LI>Secretaria: Cristina Marco.<BR>
<LI>Tesorero: Rean René Merou.<BR>
</UL>
</td>
</tr>
</table>

<BR>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>04/07/2004</td>
<td><center><b>Aprobados los Estatutos de IGLUES</b></center></td>
</tr>
<tr>
<td colspan=2>Hoy se ha hecho la redacción definitiva de los estatutos de la asociación, los cuales han sido enviados a Madrid para su aprobación.</td>
</tr>
</table>



</div>


'; 
// =================================================
</script>