<script language="php">
$title = "Otros documentos";
// =================================================
$body = '

<p>En este apartado y el anterior (manuales) de momento pondríamos enlaces 
a los sitios con documentación existente aunque deberíamos ver si es 
factible poner enlaces a la documentación específica de cada proyecto o 
bien sólo debería contener información más genérica como temas de 
economía y empresas relacionados con el software libre.</p>

'; 
// =================================================
</script>