<script language="php">
$title = "Proyectos";
// =================================================
$body = '

<H1>Proyectos</H1>


<p>En esta sección presentamos los diferentes proyectos que se suscriben a la forma de pensar de Iglues.
</p>

<h4>BULMAGES</h4>

<a href="http://bulmages.bulma.net">Página web del proyecto</a><BR>

<p>Este programa es, de momento, la estrella de la asociación. Pués es el programa bajo el que nace toda la asociación. Su misión es dotar al sistema GNU/LINUX de un programa de contabilidad (Open Source) que pueda competir con los programas comerciales existentes.</p>



<h4>BCONTAWEB</h4>

<p>Este proyecto nace para dar la capacidad a BulmaGés para ser operada a través de web. Aparte, como la programación web es algo más sencilla que la programación normal y PHP tiene capacidades de scripting que lo hacen bastante adecuado para algunas tareas se destapa con este proyecto la sincronización entre diferentes programas de un proceso empresarial.</p>

<p>El primer caso concreto que sobre el que se está trabajando es Galopin - BulmaGés.</p>

<A HREF="http://bulma.net/~tborras/bges041/bcontaweb.png"><IMG SRC="http://bulma.net/~tborras/bges041/bcontawebp.png" BORDER="0"></A>

<h4>BULMAFACT</h4>
<p>Este proyecto aun está arrancando, hay muchas ideas, una base de datos modelada y algunas pantallas. Hay algunas iniciativas y gestiones en marcha para poder hacer que este montón de buenas ideas se conviertan en una realidad, pero de momento aun esta algo verde.</p>


<h4>REPORTS</h4>

<a href="http://reports.sourceforge.net/">Página web del proyecto</a><BR>

<p>El proyecto Reports es una iniciativa de Santiago Capel (Creador de GestiONG) para generar informes de forma elegante y práctica. Utiliza plantillas XML para generar una salida y direccionarla a distintos formatos (Open Office, HTML, WEB, incluso tiene un visor própio). Este proyecto ya estaba presente en BulmaGés en la versión 0.3.1, luego por problemas de compilación se quedó en stand-by y ahora vuelve a estar incorporado dando al programa una capacidad generativa impresionante.</p>

<A HREF="http://bulma.net/~tborras/bges041/reports.png" BORDER="0"><IMG SRC="http://bulma.net/~tborras/bges041/reportsp.png" BORDER="0"></A>


<h4>ERM</h4>
<p>Ya se ha hablado de este proyecto en estas páginas. Este programa, ya maduro, cumple perfectamente con sus funciones ilustrativas de modelado de datos.</p>


<h4>GESTIONG</h4>

<a href="http://gestiong.sourceforge.net/">Página web del proyecto</a><BR>
<P>
GestiONG es un programa de gestión de ONGs y Asociaciones sin ánimo de lucro 
con un módulo de contabilidad adaptado a las necesidades especiales de estas 
asociaciones.
</P>

'; 
// =================================================
</script>