#ifndef PDEFS_PLUGINBT_ACCESOBOTONES_H
#define PDEFS_PLUGINBT_ACCESOBOTONES_H


#ifdef Q_OS_WIN32

#ifdef PLUGINBT_ACCESOBOTONES
#define PLUGINBT_ACCESOBOTONES_EXPORT __declspec(dllexport)
#else
#define PLUGINBT_ACCESOBOTONES_EXPORT __declspec(dllimport)
#endif

#else

#define PLUGINBT_ACCESOBOTONES_EXPORT

#endif


#endif

