
--
-- PostgreSQL database dump
--

SET client_encoding = 'UNICODE';
SET check_function_bodies = false;

SET search_path = public, pg_catalog;




INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (762, '4000002', 'Maquinaria Industrial S.A.'				, true, 301, FALSE, 4, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 2);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (614, '7000000', 'Ventas de mercaderias'					, true, 613, FALSE, 7, NULL, 0, 0, FALSE, FALSE, FALSE, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (767, '4300001', 'Carniceria Sibuna'					, true, 766, FALSE, 4, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 1);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (755, '1000034', 'una cuenta rara'					, true,  88, FALSE, 1, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 1);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (770, '1000000', 'Capitan Socializado'					, true, 724, FALSE, 1, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 3);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (775, '1000001', 'asdfasdf'						, true, 724, FALSE, 1, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 3);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (776, '1000002', 'asdfasdfasd'						, true, 724, FALSE, 1, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 3);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (107, '1200000', 'Remanente'						, true, 106, FALSE, 1, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 2);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (771, '7940000', 'Provision para insolvencias de trafico aplicada.'	, true, 699, FALSE, 7, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 1);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (772, '4000004', 'Adelaida'						, true, 301, FALSE, 4, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 2);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (773, '4000005', 'Hotel restaurant els NOGUERS'				, true, 301, FALSE, 4, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 2);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (768, '4300002', 'SYP - Consum'						, true, 766, FALSE, 4, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '9225665f', '', '', '', '', '', '', 1);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (764, '4000003', 'Imprenta Sa Taulera'					, true, 301, FALSE, 4, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 2);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (756, '5730001', 'SA NOSTRA'						, true, 466, FALSE, 5, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 4);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (747, '4100002', 'YACOM INTERNET FACTORY'				, true, 318, FALSE, 4, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 2);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (503, '6260000', 'Servicios bancarios y similares'			, true, 496, FALSE, 6, NULL, 0, 0, FALSE, FALSE, FALSE, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (504, '6270000', 'Publicidad, propaganda y relaciones publicas'		, true, 496, FALSE, 6, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 1);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (480, '6000000', 'Compras de mercaderias'				, true, 479, FALSE, 6, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 1);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (369, '4750000', 'Hacienda Publica, acreedor por IVA'			, true, 368, FALSE, 4, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 2);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (746, '6280004', 'SUMINISTRO ADSL'					, true, 505, FALSE, 6, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 5);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (761, '4000001', 'Ganaderias Alfredo'					, true, 301, FALSE, 4, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 2);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (769, '4300003', 'Restaurante Neirol'					, true, 766, FALSE, 4, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 1);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (752, '6280005', 'Telefonica tef'					, true, 505, FALSE, 6, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 5);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (726, '2250002', 'INMOVILIZADO CASA'					, true, 187, FALSE, 2, NULL, 0, 0, FALSE, FALSE, FALSE, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (727, '2270001', 'INMOVILIZADO COMPONENTES ORDENADOR'			, true, 189, FALSE, 2, NULL, 0, 0, FALSE, FALSE, FALSE, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (745, '6292001', 'SERVICIOS DE ASESORIA'					, true, 506, FALSE, 6, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 5);
INSERT INTO cuenta (idcuenta, codigo, descripcion, imputacion, padre, bloqueada, idgrupo, msg, debe, haber, nodebe, nohaber, regularizacion, activo, nombreent_cuenta, cifent_cuenta, dirent_cuenta, telent_cuenta, coment_cuenta, bancoent_cuenta, emailent_cuenta, webent_cuenta, tipocuenta) VALUES (742, '6296000', 'MATERIAL DE OFICINA'					, true, 506, FALSE, 6, NULL, 0, 0, FALSE, FALSE, FALSE, true, '', '', '', '', '', '', '', '', 5);


-- Como hay un trigger recursivo y hay cuentas de nivel 4 que se actualizan despues que las de nivel 1 hay que hacer el update 
-- tantas veces como niveles de cuentas tenemos.
-- El scripting de base de datos funciona muy bien.
UPDATE CUENTA SET debe=0, haber=0;
UPDATE CUENTA SET debe=0, haber=0;
UPDATE CUENTA SET debe=0, haber=0;
UPDATE CUENTA SET debe=0, haber=0;
UPDATE CUENTA SET debe=0, haber=0;
UPDATE CUENTA SET debe=0, haber=0;
UPDATE CUENTA SET debe=0, haber=0;
UPDATE CUENTA SET debe=0, haber=0;


SELECT pg_catalog.setval('cuenta_idcuenta_seq', 10000, false);


