#ifndef PDEFS_PLUGINBC_DUPLICARASIENTO_H
#define PDEFS_PLUGINBC_DUPLICARASIENTO_H


#ifdef WIN32

#ifdef PLUGINBC_DUPLICARASIENTO
#define PLUGINBC_DUPLICARASIENTO_EXPORT __declspec(dllexport)
#else
#define PLUGINBC_DUPLICARASIENTO_EXPORT __declspec(dllimport)
#endif

#else

#define PLUGINBC_DUPLICARASIENTO_EXPORT

#endif


#endif

