# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

TEMPLATE = subdirs
CONFIG += release \
warn_on \
qt
SUBDIRS += src \
           src/estadisticas 
