# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

SUBDIRS += src \
           src/estadisticas 
TEMPLATE = subdirs 
CONFIG += release \
          warn_on 
