# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

TEMPLATE = subdirs
SUBDIRS += src/estadisticas
SUBDIRS += src
SUBDIRS += src/plugin
SUBDIRS += src/plugincorrector
