#ifndef PDEFS_PLUGINBT_COBRARPARCIALIVAINCLUIDO_H
#define PDEFS_PLUGINBT_COBRARPARCIALIVAINCLUIDO_H


#ifdef Q_OS_WIN32

#ifdef PLUGINBT_COBRARPARCIALIVAINCLUIDO
#define PLUGINBT_COBRARPARCIALIVAINCLUIDO_EXPORT __declspec(dllexport)
#else
#define PLUGINBT_COBRARPARCIALIVAINCLUIDO_EXPORT __declspec(dllimport)
#endif

#else

#define PLUGINBT_COBRARPARCIALIVAINCLUIDO_EXPORT

#endif


#endif

