<table bgcolor="#AAAAAA"><TR><TD>
<A HREF="index.php">
Cambio de usuario
</A>
<BR>
<A HREF="selectempresa.php">
Seleccionar Empresa
</A>
<BR>
Balances
<BR>
<A HREF="ainteligentes.php">
Asientos Inteligentes
</A>
<BR>
Balance de Sumas y Saldos
<BR>
<A HREF="diario.php">
Diario
</A>
<BR>
<A HREF="mayor.php">
Mayor</A>
<BR>
</TD></TR>
<TR><TD>
Sincronizacion/ Importacion / Exportacion
<br>
<UL>
<A HREF="impexp.php">BulmaGés <==> Galopín v1.0</A><BR>
BulmaGés <==> Facturalux<BR>
BulmaGés <==> XML<BR>
BulmaGés <==> Contaplús<BR>
</UL></TD></TR>

</table>
