<script language="php">
$title = "Noticias";
// =================================================
$body = '

<div id="noticies">

<h1>Noticias</h1>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>11/04/2005</td>
<td><center><b>Manifestación contra las Patentes de Software</b></center></td>
</tr>
<tr>
<td colspan=2>La asociacion Iglues manifiesta su preocupación ante la propuesta de directiva aprovada por la Cominión Europea. Hace ya mucho que las asociaciones de informáticos en general se manifiestan contra la propuesta de patentes de software por sus graves consecuencias dentro del ramo del desarrollo de aplicaciones informáticas. <br>Así pues Iglues, como entidad que defiende y trabaja por la imnovación en la infiormática,  objetivo que seria según los estudios disponibles a traves de webs dedicadas al tema como proinnova o FFII  seriamente perjudicado, se une a la convocatoria de la <A href="http://movilizacion.proinnova.org/">concentración contra las patentes</A> de software del próximo 27 de abril.
</td>
</tr>
</table>

<br>


<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>12/03/2005</td>
<td><center><b>I Convención Igluera</b></center></td>
</tr>
<tr>
<td colspan=2>El pasado fin de semana tuvo lugar en Palma de Mallorca la Primera Convención Igluera. Fueron tres dias de convivencia, intercambio de opiniones, y toma de algunas decisiones. Más detalles en <A href="documentos/cronica_kedada.sxw" target="Nueva">este documento</A> y las fotos <a href="cmallorca/" target="Nueva">aquí</A>.
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>23/02/2005</td>
<td><center><b>Liberada Primera Versions de RTK::Report Toolkit</b></center></td>
</tr>
<tr>
<td colspan=2>Santiago Capel ha anunciado en la lista de correo de bulmagés la liberación de la primera versión de Reports. RTK es una grupo de herramientas bajo licencia GNU GPL para generar informes desde diferentes fuentes (que incluyen ficheros de texto plano, XML y SQL) a distintos formatos (ficheros de texto plano, HTML, OppenOffice Calc y en un visualizador gráfico propio) mediante un sistema de plantillas. 
<br><br>
Es el primer intento de crear una herramienta de generación de informes de calidad, al estilo de Crystal Reports(C), o Ms Access(C). El código está totalmente orientado a objetos y diseñado para ser extremadamente escalable, pequeño y eficiente.<br><br>
La página del proyecto es: <A href="http://reports.sourceforge.net" target="nueva">http://reports.sourceforge.net</A>  
<br><br>Cualquier comentario sobre esta herramienta podeis enviarla a Santiago Capel Torres (santiagocapel[a t]yahoo[do t]es).
<br><br><B><I>¡¡¡Enhorabuena Santi!!!</I></B>
</td>
</tr>
</table>

<br>


<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>12/02/2005</td>
<td><center><b>Presentación de BulmaGés en INTEC</b></center></td>
</tr>
<tr>
<td colspan=2>El pasado dia 12 de febrero Tomeu Borràs presentó BulmaGés en la Feria de Informática y Nuevas Tecnologías en Ibiza, invitado por el <A href="http://www.clubibosim.org" target="nueva">Club Ibosim</A>. La presentación fué un éxito teniendo en cuenta la afluencia de público al evento en general. La ponencia trató sobre nuestra asociación, el software libre y las empresas, el Proyecto BulmaGés, herramientas de desarrollo y finalizó con una pequeña demostración de los módulos BulmaCont y BulmaFact.<br>
Queremos agradecer a los miembros del <A href="http://www.clubibosim.org" target="nueva">Club Ibosim</A> su hospitalidad y las atenciones que tuvieron con nosotros. Quedamos gratamente sorprendidos de conocer más esta asociación de amigos de la informática que lleva realizado un largo camino desde sus inicios con la red Fidonet hasta la actualidad.
<br>
<A href="http://www.iglues.org/ibosim/" target="nueva">Aquí</A> podeis ver unas fotos del evento y posterior cena.
</td>
</tr>
</table>

<br>


<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>17/02/2005</td>
<td><center><b>Actualizada Documentación de RTK Reports</b></center></td>
</tr>
<tr>
<td colspan=2>El pasado dia 3 de febrero Santiago Capel actualizó la documentación de de RTK creando un pequeño tutorial que muestra 
como crear un informe a partir del fichero /etc/passwd. Está en inglés... en <A href="http://reports.sourceforge.net" target="nueva">http://reports.sourceforge.net</A><br>
<br>
También ha arreglado algunos pequeños fallos y ahora parece que está funcionando perfectamente. Con esto, se da casi por concluida la primera versión de RTK Reports.
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>16/02/2005</td>
<td><center><b>Liberada Nueva Versión BulmaGés 0.4.5</b></center></td>
</tr>
<tr>
<td colspan=2>Hoy Tomeu Borràs ha anunciado en la lista de BulmaGés la liberación de la nueva versión empaquetada 0.4.5. En ella se incluyen cambios como la entrada de líneas de IVA, gestión de cobros y pagos, además de depuración de los bugs encontrados hasta el momento de la liberación. También se han eliminado aquellas opciones que no eran operativas y que inducian a confusión, que se habían incluido en la versión anterior.<br> 
Aquel que desee ver y probar los últimos cambios del proyecto debe recurrir al CVS y compilar la versión de desarrollo, que incluye otros módulos que están en fase de desarrollo. 
<br><br>La nueva versión se puede bajar de <A href="http://prdownloads.sourceforge.net/bulmages/installbulmages_0_4_5.tgz?download" TARGET="nueva">aquí</A>. La versión de desarrollo está accesible como siempre desde el cvs de sourceforge.net.
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>31/01/2005</td>
<td><center><b>1ª Convención Igluera (2005)</b></center></td>
</tr>
<tr>
<td colspan=2>Se celebra la primera convención internacional de Iglues que tendrá lugar en Palma de Mallorca los dias 5 y 6 de Marzo:<br>
Ya han confirmado su asistencia los Iglues de Castellón y Londres  con 3 y 1 representantes.<BR>
La convención es una toma de contacto entre los distintos miembros de la Asociación y en el planing se incluye paseo marchoso por la ciudad
y degustación de platos típicos.<BR>
<BR>
Para asisistir a la convención es preciso confirmar previamente la asistencia a través de la lista.

</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>17/01/2005</td>
<td><center><b>IGLUES en eventos informáticos 2005</b></center></td>
</tr>
<tr>
<td colspan=2>Estamos muy contentos de poder comunicar que vamos a participar como ponentes en diversos eventos informáticos, jornadas de sofware libre y lan-parties. El calendario actualmente es el siguiente:<br>
        <ul>
                <li>Del 17 al 20 de Febrero: <A href="http://www.clubibosim.org" TARGET="nueva">Feria de Informática y Nuevas Tecnologías</A></li>
                <li>Dias 5, 11 al 12 de Marzo:  <A href="http://linuxcordoba.org" TARGET="nueva">Jornadas Temáticas de Software Libre de Córdoba</A></li>
                <li>Del 14 al 16 de Marzo: <A href="http://asturlinux.org/jornadas2005/index.php" TARGET="nueva">V Jornadas de Software Libre en Asturias</A></li>
                <li>Del 18 al 20 de Marzo: <A href="http://reuslanparty.org/index_es.htm" TARGET="nueva">Reus-Lan-Party</A></li>
        </ul>
        Gracias a todos por contar con nosotros :-) .

</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>21/12/2004</td>
<td><center><b>Directiva de Patentes de Programas en la lista de Puntos A del Consejo Agrícola</b></center></td>
</tr>
<tr>
<td colspan=2>Nos sentimos muy preocupados por lo que representa que la conocida como <i>"directiva de patentes de software"</i> de comisión se pueda aprovar hoy martes 21 sobre el sector informático. El mayor peligro actual para la innovacion, hasta asociaciones de informáticos se han manifestado en contra.
<br>
Más información en:
<ul>
<li><a href="http://proinnova.hispalinux.es/">Proinnova</a> [ES]
</li>
<li><a href="http://bulma.net/body.phtml?nIdNoticia=2132">Bulma.net</a> [ES]</li>
<li><a href="http://demo.ffii.org/">Acciones en la Red</a>
</li><li><a href="http://swpat.ffii.org/letter/cons0406/index.es.html">Petici&oacute;n Urgente</a> [ES]

</li><li><a href="http://kwiki.ffii.org/ConsRevers04En">Revirtamos la Decisi&oacute;n del Consejo del 18 de mayo</a>
</li>
<li><a href="http://kwiki.ffii.org/SwpatcninoEs">Noticias FFII sobre Patentes de Programaci&oacute;n</a> [ES]</li>
<li><a href="http://swpat.ffii.org/">FFII: Patentes de Programas en Europa</a>
<li><a href="http://www.nosoftwarepatents.com/es/m/intro/index.html">NoSoftwarePatents.com</a> [ES]</li>
<li><a href="http://barrapunto.com/article.pl?sid=04/12/19/0825236">Barrapunto.com</a> [ES]</li>
</ul>
<br><span style="color: rgb(255, 0, 0);">Actualizaci&oacute;n 22/12/2004:</span> La propuesta fué detenida gracias a que el representate de Polonia pidió que se borrara ese punto del acta. Se le puede dar las gracias <a href="http://thankpoland.info/" TARGET="nueva">firmando en esta carta</a>
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>5/12/2004</td>
<td><center><b>Disponible Manual de Doxigen</b></center></td>
</tr>
<tr>
<td colspan=2>El pasado día 1 de diciembre, David Gutierrez subió al CVS la primera versión del manual de Doxigen, de lectura muy recomendable especialmente para los desarrolladores. Se puede leer en la sección de <A href="http://www.iglues.org/home.php?go=manuales#doxmanual">documentación</A> de nuestra web.
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>28/11/2004</td>
<td><center><b>Junta Directiva de IGLUES</b></center></td>
</tr>
<tr>
<td colspan=2>El pasado domingo 28 de noviembre tuvo lugar la primera reunión de la nueva Junta Directiva. Cabe destacar la gran participación por parte de los soci@s tanto en asistencia como en el debate de los temas que se discutieron. En líneas generales se trataron los temas siguientes:
<ul>
<li>Creación de un inventario de proyectos en de la asociación con las personas que los integran.</li>
<li>Documentación orientada a presentar el software libre en general y el nuestro en particular a las empresas, en forma tanto de arículos como de presentacones.</li>
<li>Presentación de la asociación y de BulmaGés al Ayuntamiento de Benicarló y a AJOVE (Asociación de Jóvenes Empresarios de Castellón).</li>
<li>Realización de manuales de las aplicaciones.</li>
<li>Documentación técnica con DOXIGEN.</li>
</ul>
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>22/11/2004</td>
<td><center><b>Primer Screenshot de BfBulmaFact</b></center></td>
</tr>
<tr>
<td colspan=2>Hoy Tomeu Borràs ha mostrado la primera imagen de la futura facturación donde se pueden ver algunos de los puntos que ya se han realizado. Puede verse <A href="http://www.iglues.org/bulmafact1.png" TARGET="nueva">aquí</A>.
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>20/11/2004</td>
<td><center><b>Aplazada Junta Directiva</b></center></td>
</tr>
<tr>
<td colspan=2>Dado que en la fecha fijada para la Junta Directiva a varios de los miembros les es imposible asistir ésta se aplaza hasta el próximo domingo dia 28 de noviembre con el mismo horario y programa.
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>17/11/2004</td>
<td><center><b>Finalizado Concurso de Iconos</b></center></td>
</tr>
<tr>
<td colspan=2>Damos por concluido el concurso de icono y que tras la votación el ganador ha sido Raül. (Aunque con un margen muy muy estrecho !!!)<br>
Enhorabuena!!!!!!!!!!
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>11/11/2004</td>
<td><center><b>Reunión Junta Directiva domingo 21 de noviembre</b></center></td>
</tr>
<tr>
<td colspan=2>Se convoca reunión de la Junta Directiva para el próximo domingo 21 de noviembre a las 17:00 horas en primera convocatoria y a las 17:30 en segunda convocatoria. La reunión tratará de formalizar las responsabilidades y trazar objetivos. Podeis ver el correo de la convocatoria en la <A href="http://llistes.bulma.net/pipermail/bulmages/2004-November/001401.html">lista</A>. Sólo recordar que que por decisión en Asamblea General todos los socios son vocales de la Junta.
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>11/11/2004</td>
<td><center><b>IGLUES: Somos asociación con todas las de la Ley</b></center></td>
</tr>
<tr>
<td colspan=2>A fecha 4 de noviembre de 2004 el ministerio de interior ha resuelto en inscribir la asociación IGLUES en el Registro Nacional de Asociaciones, Grupo 1º, Sección 1ª, Número Nacional 172642. Podeis ver el comunicado realizado por nuestra secretaria en este correo de la <A href="http://llistes.bulma.net/pipermail/bulmages/2004-November/001408.html">lista</A>.
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>10/11/2004</td>
<td><center><b>Disponibles Manuales Básicos de Jabber y CVS</b></center></td>
</tr>
<tr>
<td colspan=2>Ante el interés que ha suscitado el proyecto despues de la publicación de la noticia de la creación de IGLUES en <A href="http://barrapunto.com">Barrapunto</A>, <A href="http://bulma.net">Bulma</A> y en la publicación Todo Linux, se ha creido conveniente documentar dos de los programas que nos son de utilidad en nuestro proyecto, tanto por el aspecto del desarrollo (manual de CVS) como a nivel de relación social (manual de Jabber). Ambos se encuentran en la sección de <A href="http://www.iglues.org/home.php?go=manuales">documentación</A> de nuestra web.
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>11/10/2004</td>
<td><center><b>Concurso para crear la iconografía de BulmaFact</b></center></td>
</tr>
<tr>
<td colspan=2>Ante la necesidad de realizar la iconografía para BulmaFact, se convoca un concurso consistente en
la realización de los iconos para el programa de facturación. El <A href="./img/pegatinaypin.jpg" TARGET="nueva">premio</A>, el hecho de que los iconos se utilizarán en el programa,
una pegatina y un pin de la Free Software Foundation.<br>
Los iconos a realizar son: proveedores, clientes, compras ventas, artículos, caja, bancos, facturas y partes de trabajo.</p>
<br>
Las normas del concurso son:
<ol>
        <li>No vale usar el lenguaje escrito.</li>
        <li>Los iconos deben tener 32x32 píxeles y 256 colores.</li>
        <li>Si son libres se pueden copiar o coger de otra parte.</li>
        <li>Cada participante puede presentar tantos iconos como crea oportuno.</li>
        <li>El jurado, como viene siendo habitual, será la votación popular.</li>
        <li>El plazo de presentación es el dia 11/11/2004</li>
</ol>
<p>
Se puede leer el anuncio oficial en <A HREF="http://llistes.bulma.net/pipermail/bulmages/2004-October/001201.html" TARGET="nueva">nuestra lista de correo<A>
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>06/10/2004</td>
<td><center><b>Publicada última versión de BulmaGés (0.41)</b></center></td>
</tr>
<tr>
<td colspan=2>Hoy Tomeu Borrás ha anunciado la publicación de la última versión de BulmaGés (0.41) que incluye entre otras mejoras, cambio del splash de presentación y un nuevo script de instalación.
Para más información visitar <A HREF="http://bulmages.bulma.net" TARGET="nueva">bulmages.bulma.net<A>
</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>03/10/2004</td>
<td><center><b>Primera Asamblea General</b></center></td>
</tr>
<tr>
<td colspan=2> Entre otros puntos se escogió a la nueva junta directiva que queda tal que así:
Presidente: Josep Burción, Vicepresidente: René Mérou, Secretaria: Cristina Marco. Tesorero: Tomeu Borràs<br>
Vocales: Joan Miquel Torres, Santiago Capel, Laura Edo, Pablo Braulio, Josep María Estopà<br>
El resto de socios también deberían ser vocales, según acuerdo en la asamblea. Para ello bastará la petición de serlo a la Junta Directiva.<br>
El resto de acuerdos se pueden consultar en el <a href="http://www.iglues.org/actaxxx.pdf">acta</a> de la asamblea.
</td>
</tr>
</table>

<br>


<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>17/09/2004</td>
<td><center><b>Convocatoria primera Asamblea General</b></center></td>
</tr>
<tr>
<td colspan=2>Se convoca Asamblea General de IGLUES, para tratar además de otros puntos que se pueden ver en la <a href="http://www.iglues.org/asamblea.pdf">convocatoria</a>, la elección de la Junta Directiva anual.</td>
</tr>
</table>

<br>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>25/07/2004</td>
<td><center><b>Primera Junta Directiva</b></center></td>
</tr>
<tr>
<td colspan=2>Primera Junta Directiva en la que se han tratado los temas siguientes: Logos, P&aacute;gina Web de la asociación ... </td>
</tr>
</table></table>

<br>


<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>07/07/2004</td>
<td><center><b>Nacicimiento de IGLUES</b></center></td>
</tr>
<tr>
<td colspan=2>Hoy comienza a andar la asociaci&oacute;n IGLUES, Iniciativa de Gestion Libre Universal para Empresas y Sociedades</td>
</tr>
</table>

<BR>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>05/07/2004</td>
<td><center><b>Propuesta de Junta Directiva provisional de IGLUES</b></center></td>
</tr>
<tr>
<td colspan=2>Se ha propuesto, en plan dictatorial, la junta directiva provisional de la asociación. Dicha junta tiene como misión velar por la asociación mientras esta no alcance un estado normal de funcionamiento.

Dicha Junta se compone por los siguientes cargos:<BR><BR>
<UL>
<LI>Presidente: Tomeu Borrás.<BR>
<LI>Vicepresidente 1º: Josep Burción.<BR>
<LI>Vicepresidente 2º: Joan Miquel Torres.<BR>
<LI>Secretaria: Cristina Marco.<BR>
<LI>Tesorero: Rean René Merou.<BR>
</UL>
</td>
</tr>
</table>

<BR>

<table border=0 cellspacing="0" class="news">
<tr class="head">
<td width=100>04/07/2004</td>
<td><center><b>Aprobados los Estatutos de IGLUES</b></center></td>
</tr>
<tr>
<td colspan=2>Hoy se ha hecho la redacción definitiva de los estatutos de la asociación, los cuales han sido enviados a Madrid para su aprobación.</td>
</tr>
</table>



</div>


';
// =================================================
</script>